{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.11.0.aar",
          "url": "FluctSDK-9.11.0.aar",
          "size": 467739,
          "sha512": "416e2adf398857fd0d9ff7cb22162ffb1bc5e722a18255baecf69f913a42ee2fd4363422e29b7f673a00372b0fbf1011ec35f783f18491cf4146149ca1cdb71a",
          "sha256": "7a29d6f615206898fc6f81cb7652645c04fb66c85bdf0f30654639cd44ca859a",
          "sha1": "cb0e27b3b18ca7cb56c7e104e4b3392a689daec6",
          "md5": "52e71c77bce5a2a9bd39af8109bd59cd"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.11.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.11.0.aar",
          "url": "FluctSDK-9.11.0.aar",
          "size": 467739,
          "sha512": "416e2adf398857fd0d9ff7cb22162ffb1bc5e722a18255baecf69f913a42ee2fd4363422e29b7f673a00372b0fbf1011ec35f783f18491cf4146149ca1cdb71a",
          "sha256": "7a29d6f615206898fc6f81cb7652645c04fb66c85bdf0f30654639cd44ca859a",
          "sha1": "cb0e27b3b18ca7cb56c7e104e4b3392a689daec6",
          "md5": "52e71c77bce5a2a9bd39af8109bd59cd"
        }
      ]
    }
  ]
}
