{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.1.aar",
          "url": "FluctSDK-9.9.1.aar",
          "size": 455790,
          "sha512": "de19a5891c00c9815e507d44db1ba18fc2555a01f66793bdf984fa700c761f28296cdff9c871913894761fd338846a198f29caf953e72b92d959487b2ca3051e",
          "sha256": "fbd5f9b6df7d74c5f3f3403300ba548db51077015026fa0b98c49d42227dfe2d",
          "sha1": "c6cfae6eeffe5c80c884c37c9b4f23756c1eb5a4",
          "md5": "ce7da0e82551416d22f2db4c3becec95"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.9.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.1.aar",
          "url": "FluctSDK-9.9.1.aar",
          "size": 455790,
          "sha512": "de19a5891c00c9815e507d44db1ba18fc2555a01f66793bdf984fa700c761f28296cdff9c871913894761fd338846a198f29caf953e72b92d959487b2ca3051e",
          "sha256": "fbd5f9b6df7d74c5f3f3403300ba548db51077015026fa0b98c49d42227dfe2d",
          "sha1": "c6cfae6eeffe5c80c884c37c9b4f23756c1eb5a4",
          "md5": "ce7da0e82551416d22f2db4c3becec95"
        }
      ]
    }
  ]
}
