{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "9.13.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "minimumReleaseVariantMinimumReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.8]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.13.8"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.13.8.aar",
          "url": "applovin-adapter-9.13.8.aar",
          "size": 19018,
          "sha512": "a6b662500bce3871122eaa2b7d372819d9d5afa9d0d820615e3e2821d17bacf2149768219385a019aacd678d5038bd928c8ff4d4529c5ba665037494e9e89677",
          "sha256": "aae94c118e17576e3203f2f67b1fc1f0f7d37f5467295c674f7c9df4c2f3179a",
          "sha1": "6ba22aedb760ff82e7912ce2c53c219e2addb791",
          "md5": "86608a945a245b08d58a6fe83d67c0bd"
        }
      ]
    },
    {
      "name": "minimumReleaseVariantMinimumReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.8]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.13.8"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.13.8.aar",
          "url": "applovin-adapter-9.13.8.aar",
          "size": 19018,
          "sha512": "a6b662500bce3871122eaa2b7d372819d9d5afa9d0d820615e3e2821d17bacf2149768219385a019aacd678d5038bd928c8ff4d4529c5ba665037494e9e89677",
          "sha256": "aae94c118e17576e3203f2f67b1fc1f0f7d37f5467295c674f7c9df4c2f3179a",
          "sha1": "6ba22aedb760ff82e7912ce2c53c219e2addb791",
          "md5": "86608a945a245b08d58a6fe83d67c0bd"
        }
      ]
    }
  ]
}
