{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.15.0.aar",
          "url": "fullscreen-ads-9.15.0.aar",
          "size": 139976,
          "sha512": "b065dcc4aadef09547d443d4df848291c56badb181e27403bb2c4503e22e34c46b163e8311797eb85315c7d0859131129c8c9afaa67176836c4fe7253921e40a",
          "sha256": "4f14cea7780e4ba0131fde6b89039fb9c3aa0f417ddda060649f7e9effe834a3",
          "sha1": "b59970ff74b941a87c6e905aa214f131eb1df881",
          "md5": "61a5ba69aad308a241dd69f6f3840bb7"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.15.0]"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.15.0.aar",
          "url": "fullscreen-ads-9.15.0.aar",
          "size": 139976,
          "sha512": "b065dcc4aadef09547d443d4df848291c56badb181e27403bb2c4503e22e34c46b163e8311797eb85315c7d0859131129c8c9afaa67176836c4fe7253921e40a",
          "sha256": "4f14cea7780e4ba0131fde6b89039fb9c3aa0f417ddda060649f7e9effe834a3",
          "sha1": "b59970ff74b941a87c6e905aa214f131eb1df881",
          "md5": "61a5ba69aad308a241dd69f6f3840bb7"
        }
      ]
    }
  ]
}
