{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.8.1.aar",
          "url": "FluctSDK-9.8.1.aar",
          "size": 453821,
          "sha512": "c3fbd1a557ebe463bb0e7d7a54be5ff458cf5308b5e3f0a6b2e6c81aaa765c471dc80e1026fdf2087bf1fdafb1e61d848a1ac1f1b89b8b05af91c450eae2a90c",
          "sha256": "fd7e373ca848417a90ee11ff329cc97f273b7d5403e389ae34b3c2f526e3eaab",
          "sha1": "8f7951692fe43ca15bffac539d5f9d14b2ddc12d",
          "md5": "4b010e889cc31b69b4b62afb0a68bca2"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.8.1]"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.8.1.aar",
          "url": "FluctSDK-9.8.1.aar",
          "size": 453821,
          "sha512": "c3fbd1a557ebe463bb0e7d7a54be5ff458cf5308b5e3f0a6b2e6c81aaa765c471dc80e1026fdf2087bf1fdafb1e61d848a1ac1f1b89b8b05af91c450eae2a90c",
          "sha256": "fd7e373ca848417a90ee11ff329cc97f273b7d5403e389ae34b3c2f526e3eaab",
          "sha1": "8f7951692fe43ca15bffac539d5f9d14b2ddc12d",
          "md5": "4b010e889cc31b69b4b62afb0a68bca2"
        }
      ]
    }
  ]
}
