{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.11.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.11.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.11.2.aar",
          "url": "fullscreen-ads-9.11.2.aar",
          "size": 144234,
          "sha512": "5f4dd9d429da16e2e31f21e10c06c4fd457120e6337bcf5aa59876e9fcc519c7d228de509eda03a22147c67e45509f9015349cd9d1b6cfd5fdb17bb51ec6b073",
          "sha256": "5c1d15a993cc7b45ba08eef7c3e22a351790c0d00c9306450bd6c15e007c4a4d",
          "sha1": "c4d3e1bc481a7b8b7366d4c3352b0e253af13b97",
          "md5": "b426c90ec284a866f2518831c75dc3c3"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.11.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.11.2.aar",
          "url": "fullscreen-ads-9.11.2.aar",
          "size": 144234,
          "sha512": "5f4dd9d429da16e2e31f21e10c06c4fd457120e6337bcf5aa59876e9fcc519c7d228de509eda03a22147c67e45509f9015349cd9d1b6cfd5fdb17bb51ec6b073",
          "sha256": "5c1d15a993cc7b45ba08eef7c3e22a351790c0d00c9306450bd6c15e007c4a4d",
          "sha1": "c4d3e1bc481a7b8b7366d4c3352b0e253af13b97",
          "md5": "b426c90ec284a866f2518831c75dc3c3"
        }
      ]
    }
  ]
}
