{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.8.7.aar",
          "url": "FluctSDK-9.8.7.aar",
          "size": 454406,
          "sha512": "b0f9f11962373fdb279801d578084629a92ca666597ad030908fe204dc2faab30f5055e5bb20e3c49e596551a77befe6ca1526a515de9d036828971d670bf57f",
          "sha256": "aa1fcd4d2c51ce3d230d13838abe8b4c555f2e6fd6c5bb412ee0d7842da98b8f",
          "sha1": "26dbf0cdd5a973967277e41f76857c1b19c9affa",
          "md5": "f39d68b33123ab7e9ce70e558230738e"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.8.7]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.8.7.aar",
          "url": "FluctSDK-9.8.7.aar",
          "size": 454406,
          "sha512": "b0f9f11962373fdb279801d578084629a92ca666597ad030908fe204dc2faab30f5055e5bb20e3c49e596551a77befe6ca1526a515de9d036828971d670bf57f",
          "sha256": "aa1fcd4d2c51ce3d230d13838abe8b4c555f2e6fd6c5bb412ee0d7842da98b8f",
          "sha1": "26dbf0cdd5a973967277e41f76857c1b19c9affa",
          "md5": "f39d68b33123ab7e9ce70e558230738e"
        }
      ]
    }
  ]
}
