{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.2.aar",
          "url": "fullscreen-ads-9.13.2.aar",
          "size": 143565,
          "sha512": "4bd5cc3036688b9714e9a393b2c4c588f8749180e63c81787330f0d4e1bd9724d8c33d3e50e529e6edb7f546fe6a4c0b7b10fb6cc9aa13b10030cd086bba56e2",
          "sha256": "86bda1468d87f36774d1aae4f638e0c20d9c50de929dd88080da245dbc19cb19",
          "sha1": "69f03fa1a8758214b8da0ac035c44b8c5555844a",
          "md5": "9ef966cae855aebcb8a1265dae5bf31a"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.2.aar",
          "url": "fullscreen-ads-9.13.2.aar",
          "size": 143565,
          "sha512": "4bd5cc3036688b9714e9a393b2c4c588f8749180e63c81787330f0d4e1bd9724d8c33d3e50e529e6edb7f546fe6a4c0b7b10fb6cc9aa13b10030cd086bba56e2",
          "sha256": "86bda1468d87f36774d1aae4f638e0c20d9c50de929dd88080da245dbc19cb19",
          "sha1": "69f03fa1a8758214b8da0ac035c44b8c5555844a",
          "md5": "9ef966cae855aebcb8a1265dae5bf31a"
        }
      ]
    }
  ]
}
