{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.0.aar",
          "url": "FluctSDK-9.13.0.aar",
          "size": 489170,
          "sha512": "b673c945909b8ea9ffb24769d05e3dee3684c30d36a8ee2f74aefbe7de075e4689fd3256def1af569c56be42a0f187e3b7f56b3475c7a0af13de6b52e0c97b8e",
          "sha256": "b162fa5e2614bfc1af1b9148d412f5dd9a5f34dac3c88dd706394903b7c4eef9",
          "sha1": "0f4eed23c9e28fae2affbc1bf940f39e4b7fb2b9",
          "md5": "4c02ae98a6ab45a8073234378ffa7b3b"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.13.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.0.aar",
          "url": "FluctSDK-9.13.0.aar",
          "size": 489170,
          "sha512": "b673c945909b8ea9ffb24769d05e3dee3684c30d36a8ee2f74aefbe7de075e4689fd3256def1af569c56be42a0f187e3b7f56b3475c7a0af13de6b52e0c97b8e",
          "sha256": "b162fa5e2614bfc1af1b9148d412f5dd9a5f34dac3c88dd706394903b7c4eef9",
          "sha1": "0f4eed23c9e28fae2affbc1bf940f39e4b7fb2b9",
          "md5": "4c02ae98a6ab45a8073234378ffa7b3b"
        }
      ]
    }
  ]
}
