{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.13.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.5.aar",
          "url": "FluctSDK-9.13.5.aar",
          "size": 490323,
          "sha512": "d8a8c66ee99e23dadd02814bc8979ccbf55e55888567e5e76724a77e24c2f1b4206b1f7e132f3b54984f8d4c07e298042e9b55213ff9145e8135f2bbb03df365",
          "sha256": "7e41b618168e3e923e1ea7c259bec3e3fc6c041a2eb5fbb09c95b1bbeec47faf",
          "sha1": "f68099698d012ccd051c2f17ac37ca1f2be3bf16",
          "md5": "350e4f1c7b0f4186bcfb7495a8edcbd0"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.13.5]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.5.aar",
          "url": "FluctSDK-9.13.5.aar",
          "size": 490323,
          "sha512": "d8a8c66ee99e23dadd02814bc8979ccbf55e55888567e5e76724a77e24c2f1b4206b1f7e132f3b54984f8d4c07e298042e9b55213ff9145e8135f2bbb03df365",
          "sha256": "7e41b618168e3e923e1ea7c259bec3e3fc6c041a2eb5fbb09c95b1bbeec47faf",
          "sha1": "f68099698d012ccd051c2f17ac37ca1f2be3bf16",
          "md5": "350e4f1c7b0f4186bcfb7495a8edcbd0"
        }
      ]
    }
  ]
}
