{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.14.1.aar",
          "url": "FluctSDK-9.14.1.aar",
          "size": 495357,
          "sha512": "6a24c1c188942998e09424b6afbcedf0688ca355baedb303bdf6cd391fa591fee242c557cd5c0d26fd4f6912955259bad3459039aa5902cd7e0923c1c747474f",
          "sha256": "c9c26b5a114b95b2ed8f13f4569a84d3ab47e94c0f7df92fbd978d72588b491b",
          "sha1": "da1540883289510ebaf465fef0a6fe651365819e",
          "md5": "ec4e53485a5638a8068a0509acebe040"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.14.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.14.1.aar",
          "url": "FluctSDK-9.14.1.aar",
          "size": 495357,
          "sha512": "6a24c1c188942998e09424b6afbcedf0688ca355baedb303bdf6cd391fa591fee242c557cd5c0d26fd4f6912955259bad3459039aa5902cd7e0923c1c747474f",
          "sha256": "c9c26b5a114b95b2ed8f13f4569a84d3ab47e94c0f7df92fbd978d72588b491b",
          "sha1": "da1540883289510ebaf465fef0a6fe651365819e",
          "md5": "ec4e53485a5638a8068a0509acebe040"
        }
      ]
    }
  ]
}
