{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.4.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.4.1.aar",
          "url": "FluctSDK-9.4.1.aar",
          "size": 574255,
          "sha512": "cd16b32f56b49741b8548b16dc203c7522b6ed77c51bdda9470378cfe4ebd047bd744c6035c6d35f85a4f3b063b237726cc7b782eaf3f2b8843b082456890ec9",
          "sha256": "9be239f88d75c820e3fe302311528d92e1f787091663e4d0132a531e7768f278",
          "sha1": "51977d732d1a97ff4e393f2514045e15c5e8cca8",
          "md5": "e1c8822bb304a5774fde0ab088b1e66e"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "9.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.4.1.aar",
          "url": "FluctSDK-9.4.1.aar",
          "size": 574255,
          "sha512": "cd16b32f56b49741b8548b16dc203c7522b6ed77c51bdda9470378cfe4ebd047bd744c6035c6d35f85a4f3b063b237726cc7b782eaf3f2b8843b082456890ec9",
          "sha256": "9be239f88d75c820e3fe302311528d92e1f787091663e4d0132a531e7768f278",
          "sha1": "51977d732d1a97ff4e393f2514045e15c5e8cca8",
          "md5": "e1c8822bb304a5774fde0ab088b1e66e"
        }
      ]
    }
  ]
}
