{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.13.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.12]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.12.aar",
          "url": "fullscreen-ads-9.13.12.aar",
          "size": 143516,
          "sha512": "bb91c90e811c06901994138360d5a7b5d63db31bcd61e6f28935859237c2a56c6bc2cabc09f36270dd6b88e5d00aeab11ccf04d43e39cf3f061e74a619dc2a06",
          "sha256": "4ee904a493580750ce378d09c41a4c258189bd4fbf4f22d6680b948fed8da1b3",
          "sha1": "5bdc09aec0817b2e5632e69acd0e7720173d2e89",
          "md5": "8e1456723cb37537a24e5769ab18979a"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.12]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.12.aar",
          "url": "fullscreen-ads-9.13.12.aar",
          "size": 143516,
          "sha512": "bb91c90e811c06901994138360d5a7b5d63db31bcd61e6f28935859237c2a56c6bc2cabc09f36270dd6b88e5d00aeab11ccf04d43e39cf3f061e74a619dc2a06",
          "sha256": "4ee904a493580750ce378d09c41a4c258189bd4fbf4f22d6680b948fed8da1b3",
          "sha1": "5bdc09aec0817b2e5632e69acd0e7720173d2e89",
          "md5": "8e1456723cb37537a24e5769ab18979a"
        }
      ]
    }
  ]
}
