{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.gma",
    "module": "gma-mediation",
    "version": "9.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.4.0]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.4.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.4.0.aar",
          "url": "gma-mediation-9.4.0.aar",
          "size": 49260,
          "sha512": "fe4db0fe85a8542597a7f20e7b95289308b7b40460e418b1fc57e22b94490195189d4f404efb41c5c080951e4c33cfa256d1e1e5b75c5282206809d4b01f43cf",
          "sha256": "6ad40d1784d54935020c9deac3a4f9a75ad23d2d6f9cacc65a526299ab4e2b48",
          "sha1": "89fcc2c96516c2f27162875407d5a1f0d66b0c1f",
          "md5": "ed4a14777cb9122c27011c5412e637ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "17.2.0"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.4.0]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.4.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.4.0.aar",
          "url": "gma-mediation-9.4.0.aar",
          "size": 49260,
          "sha512": "fe4db0fe85a8542597a7f20e7b95289308b7b40460e418b1fc57e22b94490195189d4f404efb41c5c080951e4c33cfa256d1e1e5b75c5282206809d4b01f43cf",
          "sha256": "6ad40d1784d54935020c9deac3a4f9a75ad23d2d6f9cacc65a526299ab4e2b48",
          "sha1": "89fcc2c96516c2f27162875407d5a1f0d66b0c1f",
          "md5": "ed4a14777cb9122c27011c5412e637ce"
        }
      ]
    }
  ]
}
