{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ah5al7rckrefjm544g7apjnem4"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.0.3]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.0.3.aar",
          "url": "fullscreen-ads-9.0.3.aar",
          "size": 119992,
          "sha512": "e77e393e5108e1a78002810890e4a6dc2f99edbdbdb00f6752cb45aa53e4a025561dc179f1da314df0f98daab108ebedeb2b9478ee771a3869ba157be1bc9f7a",
          "sha256": "c52936e1f0583aa7833795fad083a551d6fccf9d48fdbc1a846eb4124fe3d3ee",
          "sha1": "3b2afdc058f171db5ee2e7e6e69449504552c7e9",
          "md5": "742cbd18f7fb2b9b0960e88adb38de65"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.0.3]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "strictly": "[2.15.0,)",
            "requires": "[2.15.0,)",
            "prefers": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "strictly": "[2.15.0,)",
            "requires": "[2.15.0,)",
            "prefers": "2.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.0.3.aar",
          "url": "fullscreen-ads-9.0.3.aar",
          "size": 119992,
          "sha512": "e77e393e5108e1a78002810890e4a6dc2f99edbdbdb00f6752cb45aa53e4a025561dc179f1da314df0f98daab108ebedeb2b9478ee771a3869ba157be1bc9f7a",
          "sha256": "c52936e1f0583aa7833795fad083a551d6fccf9d48fdbc1a846eb4124fe3d3ee",
          "sha1": "3b2afdc058f171db5ee2e7e6e69449504552c7e9",
          "md5": "742cbd18f7fb2b9b0960e88adb38de65"
        }
      ]
    }
  ]
}
