{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.13.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.13.aar",
          "url": "FluctSDK-9.13.13.aar",
          "size": 494326,
          "sha512": "c8a6a8178ef253ab5bf6d4c5d53dfe27b726468f2e2026252e108e9ccaa56178fdd81700852bd5ea71f94bb0cfdd44df86c6cbb3bdecf7bfd1de2a371ca24b5d",
          "sha256": "0567c4c93afcad5e42fde2b17bdf6a3b921f4c6eaecb51baea4e8c1e5561030b",
          "sha1": "6263827e18f38d34c761a74cf30880105c4c01a5",
          "md5": "6b9738f4a55cda22d6a158bc5b3f448d"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.13.13]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.13.aar",
          "url": "FluctSDK-9.13.13.aar",
          "size": 494326,
          "sha512": "c8a6a8178ef253ab5bf6d4c5d53dfe27b726468f2e2026252e108e9ccaa56178fdd81700852bd5ea71f94bb0cfdd44df86c6cbb3bdecf7bfd1de2a371ca24b5d",
          "sha256": "0567c4c93afcad5e42fde2b17bdf6a3b921f4c6eaecb51baea4e8c1e5561030b",
          "sha1": "6263827e18f38d34c761a74cf30880105c4c01a5",
          "md5": "6b9738f4a55cda22d6a158bc5b3f448d"
        }
      ]
    }
  ]
}
