{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.3.1.aar",
          "url": "FluctSDK-9.3.1.aar",
          "size": 572564,
          "sha512": "cf5dc024f959ff9d689c0b577ed525bfe370fd377f9e180f68a6565e2f2c802aa1ca27652e4773d807ca762caae09213aa9d5a7a0df3f3de995d15a1db5af81b",
          "sha256": "0dc1edaf149dcbebeb9d222edc424ed4f92b19cfb8cf35a66b013bf527c53adc",
          "sha1": "4ffc9be200eb29b2669a4e19f4461fcee70abcb4",
          "md5": "6effff59da0d14681f23f99bba5c4b58"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "9.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.3.1.aar",
          "url": "FluctSDK-9.3.1.aar",
          "size": 572564,
          "sha512": "cf5dc024f959ff9d689c0b577ed525bfe370fd377f9e180f68a6565e2f2c802aa1ca27652e4773d807ca762caae09213aa9d5a7a0df3f3de995d15a1db5af81b",
          "sha256": "0dc1edaf149dcbebeb9d222edc424ed4f92b19cfb8cf35a66b013bf527c53adc",
          "sha1": "4ffc9be200eb29b2669a4e19f4461fcee70abcb4",
          "md5": "6effff59da0d14681f23f99bba5c4b58"
        }
      ]
    }
  ]
}
