{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "8.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "kru74p3uuzebzmiw4p5lvoau2q"
    }
  },
  "variants": [
    {
      "name": "productionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "FluctSDK-8.14.1.aar",
          "url": "FluctSDK-8.14.1.aar",
          "size": 584483,
          "sha512": "8a71b3b7582f49deb79106aa369a2c867a90956857852c2b2d60a2484f505dce729ac1d8e1565bdb7b7ab682262a4cd9c6fc0df1694a28acbdb10d8b20770669",
          "sha256": "1c1c2935df7e560002899182dc97297e0b94908835b57242d43a4e9d908c13df",
          "sha1": "5b3e3932e8d322d7c32c9498dc046b640690263e",
          "md5": "58180fa3b777d2d88f79ff5d17d4f741"
        }
      ]
    },
    {
      "name": "productionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-v4",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "webkit",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "8.14.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-8.14.1.aar",
          "url": "FluctSDK-8.14.1.aar",
          "size": 584483,
          "sha512": "8a71b3b7582f49deb79106aa369a2c867a90956857852c2b2d60a2484f505dce729ac1d8e1565bdb7b7ab682262a4cd9c6fc0df1694a28acbdb10d8b20770669",
          "sha256": "1c1c2935df7e560002899182dc97297e0b94908835b57242d43a4e9d908c13df",
          "sha1": "5b3e3932e8d322d7c32c9498dc046b640690263e",
          "md5": "58180fa3b777d2d88f79ff5d17d4f741"
        }
      ]
    }
  ]
}
