{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.gma",
    "module": "gma-mediation",
    "version": "9.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "minimumReleaseVariantMinimumReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.11.0]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.11.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.11.0.aar",
          "url": "gma-mediation-9.11.0.aar",
          "size": 50061,
          "sha512": "032c328732b9fb8a974a2721ac6ce52c335a1d06960d90fc09ee6660380ad5a3e347d089c4e8424e0d76431bd2421bc5fb4f2c59808e2bd8e8581dc47ed09125",
          "sha256": "74a8c69d7ac66fd643c07f3991c099bdeecb84da67b8f1c264f06fce09120fef",
          "sha1": "ed95cbd299fd4ddefc8ac8fd735c2cb82506ced5",
          "md5": "1da01ecee6364326d2bc577579759638"
        }
      ]
    },
    {
      "name": "minimumReleaseVariantMinimumReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.11.0]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.11.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.11.0.aar",
          "url": "gma-mediation-9.11.0.aar",
          "size": 50061,
          "sha512": "032c328732b9fb8a974a2721ac6ce52c335a1d06960d90fc09ee6660380ad5a3e347d089c4e8424e0d76431bd2421bc5fb4f2c59808e2bd8e8581dc47ed09125",
          "sha256": "74a8c69d7ac66fd643c07f3991c099bdeecb84da67b8f1c264f06fce09120fef",
          "sha1": "ed95cbd299fd4ddefc8ac8fd735c2cb82506ced5",
          "md5": "1da01ecee6364326d2bc577579759638"
        }
      ]
    }
  ]
}
