{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "9.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "11.5.1"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.9]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.8.9.aar",
          "url": "applovin-adapter-9.8.9.aar",
          "size": 13488,
          "sha512": "3c54702233f2ced09aef58891e6ed6f1af38a9c40107fc1d8f8e0c90e7a74941515d4319a05e0510e9515a9b554bd2a8e0033f16cf6f98f64df347934d507c9d",
          "sha256": "b0318f5f87756609ec00db6da96796f1d801b7ee4eb6dc4933ebfcb4743d588d",
          "sha1": "291b97333357f2c69653fc32e7f263e4969657df",
          "md5": "3bbc5a4bd8971043faae03bbd51a29b0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "11.5.1"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.9]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.8.9.aar",
          "url": "applovin-adapter-9.8.9.aar",
          "size": 13488,
          "sha512": "3c54702233f2ced09aef58891e6ed6f1af38a9c40107fc1d8f8e0c90e7a74941515d4319a05e0510e9515a9b554bd2a8e0033f16cf6f98f64df347934d507c9d",
          "sha256": "b0318f5f87756609ec00db6da96796f1d801b7ee4eb6dc4933ebfcb4743d588d",
          "sha1": "291b97333357f2c69653fc32e7f263e4969657df",
          "md5": "3bbc5a4bd8971043faae03bbd51a29b0"
        }
      ]
    }
  ]
}
