{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jl5uobmgs5e7vkvcjfl7d33a3m"
    }
  },
  "variants": [
    {
      "name": "productionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.1.1.aar",
          "url": "FluctSDK-9.1.1.aar",
          "size": 588735,
          "sha512": "d50607409a71179f8112cf969af99e36830b1e9c60157e4bc0e5609ff03ae5341ed4b6363c734efe53f20b62754dcec5f59ffdfa3ba535092979a315aa353508",
          "sha256": "0d432abd6ce6e3ef63625c849ceba9eec24816b8131879c091d9b065db098e5c",
          "sha1": "dbe242685bbfd1f9e481853275833f20aa16ac6a",
          "md5": "50c02843466eb134af8af46ea8e71333"
        }
      ]
    },
    {
      "name": "productionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "9.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.1.1.aar",
          "url": "FluctSDK-9.1.1.aar",
          "size": 588735,
          "sha512": "d50607409a71179f8112cf969af99e36830b1e9c60157e4bc0e5609ff03ae5341ed4b6363c734efe53f20b62754dcec5f59ffdfa3ba535092979a315aa353508",
          "sha256": "0d432abd6ce6e3ef63625c849ceba9eec24816b8131879c091d9b065db098e5c",
          "sha1": "dbe242685bbfd1f9e481853275833f20aa16ac6a",
          "md5": "50c02843466eb134af8af46ea8e71333"
        }
      ]
    }
  ]
}
