{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation",
    "module": "rewardedvideo-mediation-pangle",
    "version": "9.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.4.6]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-pangle-9.4.6.aar",
          "url": "rewardedvideo-mediation-pangle-9.4.6.aar",
          "size": 32702,
          "sha512": "ec095f18bf27585b787787b0c063bb65af8a18c24e26b1018702b073fb1d550d1bea96965ca1a05663c1cc39dc4fb4a4242c61caed7e8adace93544bf1ff5729",
          "sha256": "04b11ac4474257053923f5b76de719d37d8a7a1f9424e3c88b23aeb14ab00d13",
          "sha1": "8be21b82aa44c37f89c91a44eb636945f93b0d6c",
          "md5": "5010ff9f71cf69b2e96f48742858967c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.4.6]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.pangle.global",
          "module": "ads-sdk",
          "version": {
            "requires": "5.0.0.8"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-pangle-9.4.6.aar",
          "url": "rewardedvideo-mediation-pangle-9.4.6.aar",
          "size": 32702,
          "sha512": "ec095f18bf27585b787787b0c063bb65af8a18c24e26b1018702b073fb1d550d1bea96965ca1a05663c1cc39dc4fb4a4242c61caed7e8adace93544bf1ff5729",
          "sha256": "04b11ac4474257053923f5b76de719d37d8a7a1f9424e3c88b23aeb14ab00d13",
          "sha1": "8be21b82aa44c37f89c91a44eb636945f93b0d6c",
          "md5": "5010ff9f71cf69b2e96f48742858967c"
        }
      ]
    }
  ]
}
