{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation",
    "module": "rewardedvideo-mediation-amoad",
    "version": "9.9.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.7]"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-amoad-9.9.7.aar",
          "url": "rewardedvideo-mediation-amoad-9.9.7.aar",
          "size": 29091,
          "sha512": "ff4e626a25bb74977191c513fcd9f1d7f2e4f859db1d6801b8bf492e6826afc4c7c6f5a1dd96b98cf729d6c05ef2209cdb84363bb401e5a049bf687d4fa204dd",
          "sha256": "f746a996fd089839315ce8f8de3e2ba0426ea12eee5ff8deb12cb82381b81ccb",
          "sha1": "510d9a58c76760ce9f85f0abde1b6ecd79f9aa8c",
          "md5": "ee90a4c57f8de8084ec914c5aa615586"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amoad",
          "module": "amoad-sdk",
          "version": {
            "requires": "5.2.25"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.7]"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-amoad-9.9.7.aar",
          "url": "rewardedvideo-mediation-amoad-9.9.7.aar",
          "size": 29091,
          "sha512": "ff4e626a25bb74977191c513fcd9f1d7f2e4f859db1d6801b8bf492e6826afc4c7c6f5a1dd96b98cf729d6c05ef2209cdb84363bb401e5a049bf687d4fa204dd",
          "sha256": "f746a996fd089839315ce8f8de3e2ba0426ea12eee5ff8deb12cb82381b81ccb",
          "sha1": "510d9a58c76760ce9f85f0abde1b6ecd79f9aa8c",
          "md5": "ee90a4c57f8de8084ec914c5aa615586"
        }
      ]
    }
  ]
}
