{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.12.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.12.2.aar",
          "url": "fullscreen-ads-9.12.2.aar",
          "size": 144234,
          "sha512": "a90bc4b134b6c057d1b3c0f7a8f7232afc79f555f81e958ed55a6337a924232e3a3a1cb1b442626fcc9de33554f38f25e1dfb35b7d13a8339f8318241ce86a51",
          "sha256": "68e14450354b900e0db7add2b545a91adcba27e558da2fe84bb404a7e16be610",
          "sha1": "eb290842f5cf28bf4495450e38ffd1335c2bde7b",
          "md5": "3f09c26e9c1f7ce8c417e212599f5818"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.12.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.12.2.aar",
          "url": "fullscreen-ads-9.12.2.aar",
          "size": 144234,
          "sha512": "a90bc4b134b6c057d1b3c0f7a8f7232afc79f555f81e958ed55a6337a924232e3a3a1cb1b442626fcc9de33554f38f25e1dfb35b7d13a8339f8318241ce86a51",
          "sha256": "68e14450354b900e0db7add2b545a91adcba27e558da2fe84bb404a7e16be610",
          "sha1": "eb290842f5cf28bf4495450e38ffd1335c2bde7b",
          "md5": "3f09c26e9c1f7ce8c417e212599f5818"
        }
      ]
    }
  ]
}
