{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.8.0.aar",
          "url": "fullscreen-ads-9.8.0.aar",
          "size": 142675,
          "sha512": "f740a136578ada6576cd13c87c7f375330f9a11b02353546efdea25b3b581458ef82a48ecd53f531041ba82e9e88ef9ca0d30c593c46d4bc39004f6fc5f69434",
          "sha256": "8aa61d3927d1837460f2856fc3eca0e6d784feba7360c1e5d4c6511acbb69d46",
          "sha1": "3b2daf95ad96c489df92e0763cb5aa2d25e30fe4",
          "md5": "f456b2475ceadb9a0710cdbc5936ebaa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.8.0.aar",
          "url": "fullscreen-ads-9.8.0.aar",
          "size": 142675,
          "sha512": "f740a136578ada6576cd13c87c7f375330f9a11b02353546efdea25b3b581458ef82a48ecd53f531041ba82e9e88ef9ca0d30c593c46d4bc39004f6fc5f69434",
          "sha256": "8aa61d3927d1837460f2856fc3eca0e6d784feba7360c1e5d4c6511acbb69d46",
          "sha1": "3b2daf95ad96c489df92e0763cb5aa2d25e30fe4",
          "md5": "f456b2475ceadb9a0710cdbc5936ebaa"
        }
      ]
    }
  ]
}
