{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.13.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.6.aar",
          "url": "FluctSDK-9.13.6.aar",
          "size": 490310,
          "sha512": "15f966f4a927c3d50d192972ff1e570b02c92d3ce024a27bf9e7192782da0db656d7c3468b5e257951943116085d5178428083256e3d71bc4d76932344987a8f",
          "sha256": "936f4020c4116eb6fc71170bdbddf653f14c69a64392f030411d59a540e10ee3",
          "sha1": "eb4f1255bf016cb37f4e3cafb64bfdfa2771898d",
          "md5": "5b48a4cfcd03bd590f6b9c90b5db3c24"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.13.6]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.6.aar",
          "url": "FluctSDK-9.13.6.aar",
          "size": 490310,
          "sha512": "15f966f4a927c3d50d192972ff1e570b02c92d3ce024a27bf9e7192782da0db656d7c3468b5e257951943116085d5178428083256e3d71bc4d76932344987a8f",
          "sha256": "936f4020c4116eb6fc71170bdbddf653f14c69a64392f030411d59a540e10ee3",
          "sha1": "eb4f1255bf016cb37f4e3cafb64bfdfa2771898d",
          "md5": "5b48a4cfcd03bd590f6b9c90b5db3c24"
        }
      ]
    }
  ]
}
