{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.4.2.aar",
          "url": "FluctSDK-9.4.2.aar",
          "size": 575824,
          "sha512": "191f9dd35b31bc75d13992ec26b9a6a1454b295fc28af8c350c5528eb869a99f63026d13729fd9cfb2fb1f7e5e1a3ef41c778cb3a0762951899eafc2e6da73e5",
          "sha256": "fbebc86102ac27c86c9e59a1af8889a95f8da94dd997c64fc8730b7347e0bb55",
          "sha1": "c2b81933ac8da94946d09af1796a6a33b007c088",
          "md5": "7b665f91ff844c4b96c150091d7ba293"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "9.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.4.2.aar",
          "url": "FluctSDK-9.4.2.aar",
          "size": 575824,
          "sha512": "191f9dd35b31bc75d13992ec26b9a6a1454b295fc28af8c350c5528eb869a99f63026d13729fd9cfb2fb1f7e5e1a3ef41c778cb3a0762951899eafc2e6da73e5",
          "sha256": "fbebc86102ac27c86c9e59a1af8889a95f8da94dd997c64fc8730b7347e0bb55",
          "sha1": "c2b81933ac8da94946d09af1796a6a33b007c088",
          "md5": "7b665f91ff844c4b96c150091d7ba293"
        }
      ]
    }
  ]
}
