{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "9.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "11.5.1"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.4.4]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.4.4.aar",
          "url": "applovin-adapter-9.4.4.aar",
          "size": 13163,
          "sha512": "b18b40256c936a1307424aab3790d1c8b58a5718acf10c158f988d478f279f2a526d3ae26257a90f9d7b465d3c3ff80155eb5c6721c993f6e23fb05ea700bb5f",
          "sha256": "ae21f6c9a61cda8d744515a207f6d3af5a20f49289d071f2a5b679eb7cc41a5a",
          "sha1": "06363241901eed4ece43b82d89c0cad2ab101d09",
          "md5": "859ecbf4bedebda3bed4e15811b2e08f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "11.5.1"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.4.4]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.4.4.aar",
          "url": "applovin-adapter-9.4.4.aar",
          "size": 13163,
          "sha512": "b18b40256c936a1307424aab3790d1c8b58a5718acf10c158f988d478f279f2a526d3ae26257a90f9d7b465d3c3ff80155eb5c6721c993f6e23fb05ea700bb5f",
          "sha256": "ae21f6c9a61cda8d744515a207f6d3af5a20f49289d071f2a5b679eb7cc41a5a",
          "sha1": "06363241901eed4ece43b82d89c0cad2ab101d09",
          "md5": "859ecbf4bedebda3bed4e15811b2e08f"
        }
      ]
    }
  ]
}
