{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "9.9.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "minimumReleaseVariantMinimumReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.12]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.9.12"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.9.12.aar",
          "url": "applovin-adapter-9.9.12.aar",
          "size": 12185,
          "sha512": "ac4e069ad03b855dbe17430ad3071db59445692ea1323fce8a042f7f2c27f07464b2e22e123306574dc4de4cb6a06cd5ebdc0fd9f828ceaecbc1d769630c1b07",
          "sha256": "b932e76b4e6d569f4dcbf6520803b22e951011c3932814e6ca103518a2e707d0",
          "sha1": "51a61e969c3de51b5305bfb24a7f11c428c82a8d",
          "md5": "be9e34356c1ed32b8e80990cafc3638b"
        }
      ]
    },
    {
      "name": "minimumReleaseVariantMinimumReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.12]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.9.12"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "12.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.9.12.aar",
          "url": "applovin-adapter-9.9.12.aar",
          "size": 12185,
          "sha512": "ac4e069ad03b855dbe17430ad3071db59445692ea1323fce8a042f7f2c27f07464b2e22e123306574dc4de4cb6a06cd5ebdc0fd9f828ceaecbc1d769630c1b07",
          "sha256": "b932e76b4e6d569f4dcbf6520803b22e951011c3932814e6ca103518a2e707d0",
          "sha1": "51a61e969c3de51b5305bfb24a7f11c428c82a8d",
          "md5": "be9e34356c1ed32b8e80990cafc3638b"
        }
      ]
    }
  ]
}
