{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.13.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.3.aar",
          "url": "FluctSDK-9.13.3.aar",
          "size": 490046,
          "sha512": "b21a1ab320ae90594849a2b86950f436563539fcf41019346cb05188e9ad76cfa595a0bad241b5c547aa760e8581b5ce174abbd70dc984a6981bab05b9c347c1",
          "sha256": "c31cb61f334cb9cfeacaf355220268d150e8587fd9872c1ebd716bc8f7313d8d",
          "sha1": "d52089ddc7b7a7b8245ee6b2886d30b4e5f3af61",
          "md5": "89260ae82f7879f0c16ef0e61a0937d4"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.13.3]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.3.aar",
          "url": "FluctSDK-9.13.3.aar",
          "size": 490046,
          "sha512": "b21a1ab320ae90594849a2b86950f436563539fcf41019346cb05188e9ad76cfa595a0bad241b5c547aa760e8581b5ce174abbd70dc984a6981bab05b9c347c1",
          "sha256": "c31cb61f334cb9cfeacaf355220268d150e8587fd9872c1ebd716bc8f7313d8d",
          "sha1": "d52089ddc7b7a7b8245ee6b2886d30b4e5f3af61",
          "md5": "89260ae82f7879f0c16ef0e61a0937d4"
        }
      ]
    }
  ]
}
