{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.11.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.11.0.aar",
          "url": "fullscreen-ads-9.11.0.aar",
          "size": 144236,
          "sha512": "209878afb1d03dae3418d24801291c090fd26a96fa6ba86ca48d8bdd9313efb4ac8bd0a8e1f4e73344a2146118d7f113fcff36079631fecc81a1a83df97ffc93",
          "sha256": "14284fa8d791d1969cd393f90c9fd04cca5f7c8645c6d1308b9e4ab941bdfff3",
          "sha1": "ac25bf5e14b279d3ac66154d8d37cab471806ded",
          "md5": "4804cfee8380dbbbd9239a37b872b15c"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.11.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.11.0.aar",
          "url": "fullscreen-ads-9.11.0.aar",
          "size": 144236,
          "sha512": "209878afb1d03dae3418d24801291c090fd26a96fa6ba86ca48d8bdd9313efb4ac8bd0a8e1f4e73344a2146118d7f113fcff36079631fecc81a1a83df97ffc93",
          "sha256": "14284fa8d791d1969cd393f90c9fd04cca5f7c8645c6d1308b9e4ab941bdfff3",
          "sha1": "ac25bf5e14b279d3ac66154d8d37cab471806ded",
          "md5": "4804cfee8380dbbbd9239a37b872b15c"
        }
      ]
    }
  ]
}
