{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "shared",
    "version": "9.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "shared-9.15.0.aar",
          "url": "shared-9.15.0.aar",
          "size": 59460,
          "sha512": "c1eb4190ccbfc254c05fffec411860c0823e23c69e196d9dc19c8f90d7380df0d5645b7b72144342326cb79d0d7e507e1ab907ae411257e4649580a4d86450a0",
          "sha256": "a75f08bc7b065bb82927601ef5deaf67f6245459d97a61006d8e9b461dc6c2bc",
          "sha1": "2ef0dd37ec0db763d2829d34c89172c3ed42da98",
          "md5": "0b0a7934d8102a47a180f0df179297a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "shared-9.15.0.aar",
          "url": "shared-9.15.0.aar",
          "size": 59460,
          "sha512": "c1eb4190ccbfc254c05fffec411860c0823e23c69e196d9dc19c8f90d7380df0d5645b7b72144342326cb79d0d7e507e1ab907ae411257e4649580a4d86450a0",
          "sha256": "a75f08bc7b065bb82927601ef5deaf67f6245459d97a61006d8e9b461dc6c2bc",
          "sha1": "2ef0dd37ec0db763d2829d34c89172c3ed42da98",
          "md5": "0b0a7934d8102a47a180f0df179297a0"
        }
      ]
    }
  ]
}
