{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "9.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "strictly": "[11.4.0,)",
            "requires": "[11.4.0,)",
            "prefers": "11.4.4"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "9.0.0",
            "prefers": "9.0.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.0.0",
            "prefers": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.0.0.aar",
          "url": "applovin-adapter-9.0.0.aar",
          "size": 13163,
          "sha512": "f103ba83bd6a8638e2447ac86ee3bdd95aafe3868c4ca029a1229ac17b8e5da6221588943b110ae8c325acbb3ce97437b93bbada3bafaaefdb9cc4835ff28d33",
          "sha256": "a978b0d19d37850d63b758a518e5b75ac4f1bf75a9b794d6477682420b82db0f",
          "sha1": "5904264c0b5f0dede5e471f5e7c15f96c9fdfd58",
          "md5": "8f182a8cb09ad7862aad4dedb66fa834"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "strictly": "[11.4.0,)",
            "requires": "[11.4.0,)",
            "prefers": "11.4.4"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "9.0.0",
            "prefers": "9.0.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.0.0",
            "prefers": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.0.0.aar",
          "url": "applovin-adapter-9.0.0.aar",
          "size": 13163,
          "sha512": "f103ba83bd6a8638e2447ac86ee3bdd95aafe3868c4ca029a1229ac17b8e5da6221588943b110ae8c325acbb3ce97437b93bbada3bafaaefdb9cc4835ff28d33",
          "sha256": "a978b0d19d37850d63b758a518e5b75ac4f1bf75a9b794d6477682420b82db0f",
          "sha1": "5904264c0b5f0dede5e471f5e7c15f96c9fdfd58",
          "md5": "8f182a8cb09ad7862aad4dedb66fa834"
        }
      ]
    }
  ]
}
