{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.4]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.9.4.aar",
          "url": "fullscreen-ads-9.9.4.aar",
          "size": 143691,
          "sha512": "e75f7857a7ad1b22a51969218010d76415ffd6ebc6aba8e8853056c7225a175427d5eb700082057b7c32ecfa0f4533399db7e4653fc1e05eebb7eeeda8cdfc3f",
          "sha256": "7f5cb9e9f9e433b25043a407d47b60ccde28993f907c4f714b11bfc597ba696b",
          "sha1": "56c10927e4bf5f4ee57b19201a3bec93ac7be898",
          "md5": "6ca5a269837d5784e43ced8dc4ec3ec3"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.4]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.9.4.aar",
          "url": "fullscreen-ads-9.9.4.aar",
          "size": 143691,
          "sha512": "e75f7857a7ad1b22a51969218010d76415ffd6ebc6aba8e8853056c7225a175427d5eb700082057b7c32ecfa0f4533399db7e4653fc1e05eebb7eeeda8cdfc3f",
          "sha256": "7f5cb9e9f9e433b25043a407d47b60ccde28993f907c4f714b11bfc597ba696b",
          "sha1": "56c10927e4bf5f4ee57b19201a3bec93ac7be898",
          "md5": "6ca5a269837d5784e43ced8dc4ec3ec3"
        }
      ]
    }
  ]
}
