{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "shared",
    "version": "9.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "shared-9.16.1.aar",
          "url": "shared-9.16.1.aar",
          "size": 82235,
          "sha512": "50ceb59d1da4b2e37c57d7955f646a66c5400eb7716238cc64d2555d942209e356c62e0fb79c8b4e9544e45dfe2108d6c9b36aba62067aafd2c0f9624d8d1782",
          "sha256": "315894966f1358f7f1d6ae12570aead01e419342df0a0419827512670a997fdf",
          "sha1": "7c15bf741965251059aee110f569375b2f9d0e05",
          "md5": "44e0a01b7bdde6f42d0c9726313ee1ee"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "shared-9.16.1.aar",
          "url": "shared-9.16.1.aar",
          "size": 82235,
          "sha512": "50ceb59d1da4b2e37c57d7955f646a66c5400eb7716238cc64d2555d942209e356c62e0fb79c8b4e9544e45dfe2108d6c9b36aba62067aafd2c0f9624d8d1782",
          "sha256": "315894966f1358f7f1d6ae12570aead01e419342df0a0419827512670a997fdf",
          "sha1": "7c15bf741965251059aee110f569375b2f9d0e05",
          "md5": "44e0a01b7bdde6f42d0c9726313ee1ee"
        }
      ]
    }
  ]
}
