{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.6.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.6.1.aar",
          "url": "fullscreen-ads-9.6.1.aar",
          "size": 136417,
          "sha512": "d00bca76a401db0241855d5c670388e656a0e6434a5353c48fc09c4286cfc786949c61ddc3e3b22679f29864c7b552b7166958b1594f9b7ea3661d3494b8d647",
          "sha256": "8929c24b457a38ca42dd118cefbcc3efea783d01680c9c0cd6b3f02c36f07718",
          "sha1": "4a939385810cb5d49180af85e50a4407d9a0c56e",
          "md5": "40d2f8fc98fba1228896decb0c0f46bb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.6.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.6.1.aar",
          "url": "fullscreen-ads-9.6.1.aar",
          "size": 136417,
          "sha512": "d00bca76a401db0241855d5c670388e656a0e6434a5353c48fc09c4286cfc786949c61ddc3e3b22679f29864c7b552b7166958b1594f9b7ea3661d3494b8d647",
          "sha256": "8929c24b457a38ca42dd118cefbcc3efea783d01680c9c0cd6b3f02c36f07718",
          "sha1": "4a939385810cb5d49180af85e50a4407d9a0c56e",
          "md5": "40d2f8fc98fba1228896decb0c0f46bb"
        }
      ]
    }
  ]
}
