{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.13.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.12.aar",
          "url": "FluctSDK-9.13.12.aar",
          "size": 494346,
          "sha512": "a3293110dbaed10ed167d77da161ce27f71d2511612f9684fdbea1715d6ea5d3bc3bea1f4c4a724b0bcc69bcfafc20edc3eb979db94b2afe5672a96ff0497dfd",
          "sha256": "e6b374a9a44a0337434ee45743a5d191bb6a6c987d5f1826611d2c74588b383c",
          "sha1": "e211a5db038a4e6303a12edbb0a4d645a8f8e5b6",
          "md5": "3b808a5e2a221246ac89eb93dd8bc765"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.13.12]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.12.aar",
          "url": "FluctSDK-9.13.12.aar",
          "size": 494346,
          "sha512": "a3293110dbaed10ed167d77da161ce27f71d2511612f9684fdbea1715d6ea5d3bc3bea1f4c4a724b0bcc69bcfafc20edc3eb979db94b2afe5672a96ff0497dfd",
          "sha256": "e6b374a9a44a0337434ee45743a5d191bb6a6c987d5f1826611d2c74588b383c",
          "sha1": "e211a5db038a4e6303a12edbb0a4d645a8f8e5b6",
          "md5": "3b808a5e2a221246ac89eb93dd8bc765"
        }
      ]
    }
  ]
}
