{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "9.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "minimumReleaseVariantMinimumReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.12.1]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.12.1"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "12.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.12.1.aar",
          "url": "applovin-adapter-9.12.1.aar",
          "size": 18947,
          "sha512": "4d920138164ebb137651c4be52d29de8d9ae3b9b94bb80d36e9b37f446ca10a34ad597ad58f94e21acb10d51b53cbb58c2230752345d925fb2753bd57a3d7e17",
          "sha256": "0bb6ac59f1184635a94b76d94846d75b47b09ea20206cdf692162c4322c33116",
          "sha1": "b5598a8bd37cc8add5738a1b0744ab82f1b0a4bd",
          "md5": "245bc4a7bfbb5f72001c957236853611"
        }
      ]
    },
    {
      "name": "minimumReleaseVariantMinimumReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.12.1]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.12.1"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "12.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.12.1.aar",
          "url": "applovin-adapter-9.12.1.aar",
          "size": 18947,
          "sha512": "4d920138164ebb137651c4be52d29de8d9ae3b9b94bb80d36e9b37f446ca10a34ad597ad58f94e21acb10d51b53cbb58c2230752345d925fb2753bd57a3d7e17",
          "sha256": "0bb6ac59f1184635a94b76d94846d75b47b09ea20206cdf692162c4322c33116",
          "sha1": "b5598a8bd37cc8add5738a1b0744ab82f1b0a4bd",
          "md5": "245bc4a7bfbb5f72001c957236853611"
        }
      ]
    }
  ]
}
