{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.7.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.7.0.aar",
          "url": "fullscreen-ads-9.7.0.aar",
          "size": 142675,
          "sha512": "ebbe9ce1814e9f92acc8945ea14c969f604206f0d4bd2ff723c8a1ff1a8de298f4dd7a998e74f94f6062f3c9491504fd16c44d0611d3c194f283643c275a8812",
          "sha256": "889f0792657b6b4e41bf4ca274737d8235a74d5ea825582ac568545613252c81",
          "sha1": "bc2f94a40ecc03bc69628aa3e114505f302b90ab",
          "md5": "01717949e04ba3d806fb791c5f92f38a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.7.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.7.0.aar",
          "url": "fullscreen-ads-9.7.0.aar",
          "size": 142675,
          "sha512": "ebbe9ce1814e9f92acc8945ea14c969f604206f0d4bd2ff723c8a1ff1a8de298f4dd7a998e74f94f6062f3c9491504fd16c44d0611d3c194f283643c275a8812",
          "sha256": "889f0792657b6b4e41bf4ca274737d8235a74d5ea825582ac568545613252c81",
          "sha1": "bc2f94a40ecc03bc69628aa3e114505f302b90ab",
          "md5": "01717949e04ba3d806fb791c5f92f38a"
        }
      ]
    }
  ]
}
