{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.15.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.5]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.15.5.aar",
          "url": "fullscreen-ads-9.15.5.aar",
          "size": 145902,
          "sha512": "95d9557de5394549af848b174bd347f75a5fcb8a5f6b0e92ad50f20e905bbd80a901e724dd1e64558fc0511a439a9c82ecf63d39edc804363a18517985b8841b",
          "sha256": "e232ce7b66b5c3ca25772718cadd2d7ba779e432ebe9217b2b07a134bc7c9d1e",
          "sha1": "8288d9b1584e2822bb71434aa02ecba7e61d7dcb",
          "md5": "fc09c96430ba541e723fec8deaf50b89"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.15.5]"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.5]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.15.5.aar",
          "url": "fullscreen-ads-9.15.5.aar",
          "size": 145902,
          "sha512": "95d9557de5394549af848b174bd347f75a5fcb8a5f6b0e92ad50f20e905bbd80a901e724dd1e64558fc0511a439a9c82ecf63d39edc804363a18517985b8841b",
          "sha256": "e232ce7b66b5c3ca25772718cadd2d7ba779e432ebe9217b2b07a134bc7c9d1e",
          "sha1": "8288d9b1584e2822bb71434aa02ecba7e61d7dcb",
          "md5": "fc09c96430ba541e723fec8deaf50b89"
        }
      ]
    }
  ]
}
