{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "8.14.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ziuerdkvgbfivpt46qw7pfbade"
    }
  },
  "variants": [
    {
      "name": "productionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "FluctSDK-8.14.2.aar",
          "url": "FluctSDK-8.14.2.aar",
          "size": 585435,
          "sha512": "efecc7ed65d99df5dcae0784c77b100bb7515ba5121ea4c2e857c0733200c4a6f82d5e39c11478ebccd64d0b5bf03e9067b4b435f9942eeee7fe27499a92bdc5",
          "sha256": "1a00022ce9233cb4378f427ca301db3ed70426dbccd36521f21c0ad1395a9e3e",
          "sha1": "35a574c9aa581fb5723dd9d8a21beb59d21fc78f",
          "md5": "3ddfe066728a7ee770f343ff4897ce60"
        }
      ]
    },
    {
      "name": "productionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-v4",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "webkit",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "8.14.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-8.14.2.aar",
          "url": "FluctSDK-8.14.2.aar",
          "size": 585435,
          "sha512": "efecc7ed65d99df5dcae0784c77b100bb7515ba5121ea4c2e857c0733200c4a6f82d5e39c11478ebccd64d0b5bf03e9067b4b435f9942eeee7fe27499a92bdc5",
          "sha256": "1a00022ce9233cb4378f427ca301db3ed70426dbccd36521f21c0ad1395a9e3e",
          "sha1": "35a574c9aa581fb5723dd9d8a21beb59d21fc78f",
          "md5": "3ddfe066728a7ee770f343ff4897ce60"
        }
      ]
    }
  ]
}
