{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.15.1.aar",
          "url": "FluctSDK-9.15.1.aar",
          "size": 477829,
          "sha512": "1c1f32f955b5717baa1a71870df3376d2d1721a579762be8ef465a0f6803b7880d05377ac6dd79f2acafcabd9c4db9687110f5b50bafa77573c517e870292368",
          "sha256": "5b005d2bdd515edaf7cd78673d90eb1c7f7a4737e8d1b92106bb533a025207e1",
          "sha1": "f61c3f1aad0453a92369dc5ad5ce509fc14eb599",
          "md5": "673025bf52db642c4d12ae8565184011"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.15.1]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.15.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.15.1.aar",
          "url": "FluctSDK-9.15.1.aar",
          "size": 477829,
          "sha512": "1c1f32f955b5717baa1a71870df3376d2d1721a579762be8ef465a0f6803b7880d05377ac6dd79f2acafcabd9c4db9687110f5b50bafa77573c517e870292368",
          "sha256": "5b005d2bdd515edaf7cd78673d90eb1c7f7a4737e8d1b92106bb533a025207e1",
          "sha1": "f61c3f1aad0453a92369dc5ad5ce509fc14eb599",
          "md5": "673025bf52db642c4d12ae8565184011"
        }
      ]
    }
  ]
}
