{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "shared",
    "version": "9.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "shared-9.15.4.aar",
          "url": "shared-9.15.4.aar",
          "size": 80989,
          "sha512": "630b650c10a67a6c76c516d84ff3eaea2971c5110490ff0349625dcb57e3db4af8f7e9454a3197003086357694222219ee1a7773e368202063bc198f07627e7f",
          "sha256": "dbcf9876b13f5b61a6db4d521475aeb48bf1d5703f289fcebb89081abbc2edc6",
          "sha1": "1ac1ae63b1e78e4004c884b3c7b9ae6510d2046d",
          "md5": "a08a08692ff26d89b430953914a51216"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "shared-9.15.4.aar",
          "url": "shared-9.15.4.aar",
          "size": 80989,
          "sha512": "630b650c10a67a6c76c516d84ff3eaea2971c5110490ff0349625dcb57e3db4af8f7e9454a3197003086357694222219ee1a7773e368202063bc198f07627e7f",
          "sha256": "dbcf9876b13f5b61a6db4d521475aeb48bf1d5703f289fcebb89081abbc2edc6",
          "sha1": "1ac1ae63b1e78e4004c884b3c7b9ae6510d2046d",
          "md5": "a08a08692ff26d89b430953914a51216"
        }
      ]
    }
  ]
}
