{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.13.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.14]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.14.aar",
          "url": "fullscreen-ads-9.13.14.aar",
          "size": 143431,
          "sha512": "cae227e5f4dfa1025974d5d3bc07e65495e0832c1a21ee0805f156d3034d56a01483a706cd3d2dbd08e6a8419894de4083c7c26e64434146a845c7df74279692",
          "sha256": "5795a9c1938a650c2861ddfefce5616f568886c1fb7fb7ee0aee36700785fcc1",
          "sha1": "eb9806375a1f0e364a0582bf0f7b86f01bc75205",
          "md5": "e77f9b453d5ca10fedbc8fe8bc76e54d"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.14]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.14.aar",
          "url": "fullscreen-ads-9.13.14.aar",
          "size": 143431,
          "sha512": "cae227e5f4dfa1025974d5d3bc07e65495e0832c1a21ee0805f156d3034d56a01483a706cd3d2dbd08e6a8419894de4083c7c26e64434146a845c7df74279692",
          "sha256": "5795a9c1938a650c2861ddfefce5616f568886c1fb7fb7ee0aee36700785fcc1",
          "sha1": "eb9806375a1f0e364a0582bf0f7b86f01bc75205",
          "md5": "e77f9b453d5ca10fedbc8fe8bc76e54d"
        }
      ]
    }
  ]
}
