{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.8.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.8.3.aar",
          "url": "FluctSDK-9.8.3.aar",
          "size": 453826,
          "sha512": "8caee8c31a6008446b88a84e7f3e3fe5fdd642e26e94d91a5ca2d30d18f220490bcbfc78b3d954cb41101cc881db82ea3f7be13d9616a18e4353e1df64208046",
          "sha256": "c574f567e719345430c0012a5c334d8c38660c34161bbc4dac1aa95535fe2ea2",
          "sha1": "0cf0ecabf987e405d642731f68c4a7d5367641d0",
          "md5": "0772f969de8015e1e3be06144ad77809"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.8.3]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.8.3.aar",
          "url": "FluctSDK-9.8.3.aar",
          "size": 453826,
          "sha512": "8caee8c31a6008446b88a84e7f3e3fe5fdd642e26e94d91a5ca2d30d18f220490bcbfc78b3d954cb41101cc881db82ea3f7be13d9616a18e4353e1df64208046",
          "sha256": "c574f567e719345430c0012a5c334d8c38660c34161bbc4dac1aa95535fe2ea2",
          "sha1": "0cf0ecabf987e405d642731f68c4a7d5367641d0",
          "md5": "0772f969de8015e1e3be06144ad77809"
        }
      ]
    }
  ]
}
