{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.13.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.11.aar",
          "url": "FluctSDK-9.13.11.aar",
          "size": 494342,
          "sha512": "25f11a3d324181265d9c5cad0f34f67435ebb1517a8678083babd35919d4e041e95aa5d937b8b384c6b9f1771b5c470c9cbdc5b2997ffeeab94d32f9bfeee826",
          "sha256": "85912def5bdb246d705869f668097aa5c442158f66370eb59513c6f40424e2a0",
          "sha1": "60d4cfa50f53a344d1feae7c4b2a2770ccb3dd61",
          "md5": "b29f8f5c8458442f1b7653e45e4929c9"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.13.11]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.11.aar",
          "url": "FluctSDK-9.13.11.aar",
          "size": 494342,
          "sha512": "25f11a3d324181265d9c5cad0f34f67435ebb1517a8678083babd35919d4e041e95aa5d937b8b384c6b9f1771b5c470c9cbdc5b2997ffeeab94d32f9bfeee826",
          "sha256": "85912def5bdb246d705869f668097aa5c442158f66370eb59513c6f40424e2a0",
          "sha1": "60d4cfa50f53a344d1feae7c4b2a2770ccb3dd61",
          "md5": "b29f8f5c8458442f1b7653e45e4929c9"
        }
      ]
    }
  ]
}
