{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.6]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.8.6.aar",
          "url": "fullscreen-ads-9.8.6.aar",
          "size": 142747,
          "sha512": "179e5e936a4e3e86b124a610f3cc9cc55759eebb0250b5ec3ac11d119114f8a01944c5fa5fdcb5bb7f68d87ceafe7ad7d24590b667ca33c9eae8111bcb432884",
          "sha256": "dcbb1a7da9bdffeec5a1021c10fabefd4e54fd62b6ae5a3884fece42e7c0a036",
          "sha1": "fdfe50961f6655e8301ea0ba76070b00e8ff968d",
          "md5": "bf5913666a5a82c963c5336a906bca37"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.6]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.8.6.aar",
          "url": "fullscreen-ads-9.8.6.aar",
          "size": 142747,
          "sha512": "179e5e936a4e3e86b124a610f3cc9cc55759eebb0250b5ec3ac11d119114f8a01944c5fa5fdcb5bb7f68d87ceafe7ad7d24590b667ca33c9eae8111bcb432884",
          "sha256": "dcbb1a7da9bdffeec5a1021c10fabefd4e54fd62b6ae5a3884fece42e7c0a036",
          "sha1": "fdfe50961f6655e8301ea0ba76070b00e8ff968d",
          "md5": "bf5913666a5a82c963c5336a906bca37"
        }
      ]
    }
  ]
}
