{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "shared",
    "version": "9.15.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "shared-9.15.5.aar",
          "url": "shared-9.15.5.aar",
          "size": 82241,
          "sha512": "ec9a11f541235071aeae6d587fa5417e5d58db7348ec1594e667464f8396fb075fb42c522df21bd93504671933099bffd1c66bc27a085e384975691786c79ef3",
          "sha256": "f4eb7bddbe4f56a93e4bc1a5b80d17a56122d95ed19981accbd9d274c242c612",
          "sha1": "48f3707fd0546a4ae3668b105ff7c405690b988e",
          "md5": "acbf60f74f919ebf85c464b21a7fd2f9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "shared-9.15.5.aar",
          "url": "shared-9.15.5.aar",
          "size": 82241,
          "sha512": "ec9a11f541235071aeae6d587fa5417e5d58db7348ec1594e667464f8396fb075fb42c522df21bd93504671933099bffd1c66bc27a085e384975691786c79ef3",
          "sha256": "f4eb7bddbe4f56a93e4bc1a5b80d17a56122d95ed19981accbd9d274c242c612",
          "sha1": "48f3707fd0546a4ae3668b105ff7c405690b988e",
          "md5": "acbf60f74f919ebf85c464b21a7fd2f9"
        }
      ]
    }
  ]
}
