{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "8.12.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "uod4k7amebet3oav5plfmy44xy"
    }
  },
  "variants": [
    {
      "name": "productionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "FluctSDK-8.12.3.aar",
          "url": "FluctSDK-8.12.3.aar",
          "size": 583825,
          "sha512": "cd94ee2fda9efa65a289f6e37dd94e438d1f508349ff611f35a13028f27e20960af143c278dcadb3acf87636637af3eb1f98b288eee07ccec78e0b8396caa722",
          "sha256": "06776a0536a5bedd78396feade89f5801a290d8be2c23e1f5c8c24e0e52b2224",
          "sha1": "1e8fca6c7ab67306d99ba623bfce2dd0a1aaed72",
          "md5": "504e7e3861e2958e4a2f604e6c002215"
        }
      ]
    },
    {
      "name": "productionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-v4",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "webkit",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "8.12.3"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-8.12.3.aar",
          "url": "FluctSDK-8.12.3.aar",
          "size": 583825,
          "sha512": "cd94ee2fda9efa65a289f6e37dd94e438d1f508349ff611f35a13028f27e20960af143c278dcadb3acf87636637af3eb1f98b288eee07ccec78e0b8396caa722",
          "sha256": "06776a0536a5bedd78396feade89f5801a290d8be2c23e1f5c8c24e0e52b2224",
          "sha1": "1e8fca6c7ab67306d99ba623bfce2dd0a1aaed72",
          "md5": "504e7e3861e2958e4a2f604e6c002215"
        }
      ]
    }
  ]
}
