{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "9.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "minimumReleaseVariantMinimumReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.16.2]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.16.2"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.16.2.aar",
          "url": "applovin-adapter-9.16.2.aar",
          "size": 19024,
          "sha512": "bd333dd0874910720350c2f3e8cad3fd97e1ae5ac99075f8d1d377364c7ebe869151f08e94656661eb906cd64d4dc8744fe109d10a5e1d70b72b7afa1fb04e82",
          "sha256": "a221602a69790c8ce271eda9041ff41dd94dffba7b6daa195997cfeefd87b453",
          "sha1": "79ba6d2944f41fd30b187d5e41e1caec8538678f",
          "md5": "b7b1e2e53f9458fd9f1e51e3c2cb8418"
        }
      ]
    },
    {
      "name": "minimumReleaseVariantMinimumReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.16.2]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.16.2"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.16.2.aar",
          "url": "applovin-adapter-9.16.2.aar",
          "size": 19024,
          "sha512": "bd333dd0874910720350c2f3e8cad3fd97e1ae5ac99075f8d1d377364c7ebe869151f08e94656661eb906cd64d4dc8744fe109d10a5e1d70b72b7afa1fb04e82",
          "sha256": "a221602a69790c8ce271eda9041ff41dd94dffba7b6daa195997cfeefd87b453",
          "sha1": "79ba6d2944f41fd30b187d5e41e1caec8538678f",
          "md5": "b7b1e2e53f9458fd9f1e51e3c2cb8418"
        }
      ]
    }
  ]
}
