{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.13.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.13]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.13.aar",
          "url": "fullscreen-ads-9.13.13.aar",
          "size": 143525,
          "sha512": "2bdf6c77845979c8c4b6b536023fa9847f2b9791de104929ff66c752f32d7c0d622f04f95618ccb907d514367a182205909929cf2c9c47434ecc71e49c581c71",
          "sha256": "97022e86577fad2129f8218f850d3106677bb25a786314bcd48a81d6bb26700b",
          "sha1": "993d4a88d443712cf013691bb4d4fb5a416b4d56",
          "md5": "b9e9bf9e725d00fed928d4c31a37a8d5"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.13]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.13.aar",
          "url": "fullscreen-ads-9.13.13.aar",
          "size": 143525,
          "sha512": "2bdf6c77845979c8c4b6b536023fa9847f2b9791de104929ff66c752f32d7c0d622f04f95618ccb907d514367a182205909929cf2c9c47434ecc71e49c581c71",
          "sha256": "97022e86577fad2129f8218f850d3106677bb25a786314bcd48a81d6bb26700b",
          "sha1": "993d4a88d443712cf013691bb4d4fb5a416b4d56",
          "md5": "b9e9bf9e725d00fed928d4c31a37a8d5"
        }
      ]
    }
  ]
}
