{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.4]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.15.4.aar",
          "url": "fullscreen-ads-9.15.4.aar",
          "size": 145901,
          "sha512": "e2c4613070771a602d8d73e3bb55acca2795607fc129d900d1c18e5ecfef10b585fed9016027604f0f94bcf65b0b96c1cf0c8d575d28a4ba56e1c70217a58c20",
          "sha256": "0ad7daba168b0bb5fd0017a4b4693936cf0d6fc843a4ba5666edda338457230f",
          "sha1": "9299eb2a2593e9d6fbcec6d44dfc5343f2cdb0f6",
          "md5": "da4fb1d29c4fb109ba70d3c8e7e6c056"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.15.4]"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.4]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.15.4.aar",
          "url": "fullscreen-ads-9.15.4.aar",
          "size": 145901,
          "sha512": "e2c4613070771a602d8d73e3bb55acca2795607fc129d900d1c18e5ecfef10b585fed9016027604f0f94bcf65b0b96c1cf0c8d575d28a4ba56e1c70217a58c20",
          "sha256": "0ad7daba168b0bb5fd0017a4b4693936cf0d6fc843a4ba5666edda338457230f",
          "sha1": "9299eb2a2593e9d6fbcec6d44dfc5343f2cdb0f6",
          "md5": "da4fb1d29c4fb109ba70d3c8e7e6c056"
        }
      ]
    }
  ]
}
