{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "8.12.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "qelaf6232bfi3jl4jv6ov4fbmu"
    }
  },
  "variants": [
    {
      "name": "productionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "FluctSDK-8.12.5.aar",
          "url": "FluctSDK-8.12.5.aar",
          "size": 583135,
          "sha512": "0cf721ea6e73d4c206ea8cd538cb42d0703d665c9448397bfcceb36d442a7c9967f075fdc53fb566ac079ecdfac51742ef89bf00f2a3792d87e171d16fe7e24e",
          "sha256": "41809b6169033c8ab5a77c77ca26cd0d60abf536a0afb695e7a07dd8d72b4ea6",
          "sha1": "98390d7cb24c07596765558cdfdc7a6ceb7586ee",
          "md5": "2fd9384ed32d3def5b219e3c3617b732"
        }
      ]
    },
    {
      "name": "productionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-v4",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "webkit",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "8.12.5"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-8.12.5.aar",
          "url": "FluctSDK-8.12.5.aar",
          "size": 583135,
          "sha512": "0cf721ea6e73d4c206ea8cd538cb42d0703d665c9448397bfcceb36d442a7c9967f075fdc53fb566ac079ecdfac51742ef89bf00f2a3792d87e171d16fe7e24e",
          "sha256": "41809b6169033c8ab5a77c77ca26cd0d60abf536a0afb695e7a07dd8d72b4ea6",
          "sha1": "98390d7cb24c07596765558cdfdc7a6ceb7586ee",
          "md5": "2fd9384ed32d3def5b219e3c3617b732"
        }
      ]
    }
  ]
}
