{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.6]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.9.6.aar",
          "url": "fullscreen-ads-9.9.6.aar",
          "size": 143695,
          "sha512": "1d3be4c23a1534fe771742eb7d66b20309de9c6a6d28cc8e4728dfe9cea4b7eba1f14b1c6aea27469df086eb4acadc6a092afb376ca7689ecf7bf2d3c6fcfc75",
          "sha256": "d18ba34f174aafd8ac66b70be190af6f5aa8d8ce3c6e3c45f5b09c732095a38c",
          "sha1": "42ae5fc16e387d2f62971d12c707a15b43c30f1e",
          "md5": "2253806f40e4907722a4529ada97f93d"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.6]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.9.6.aar",
          "url": "fullscreen-ads-9.9.6.aar",
          "size": 143695,
          "sha512": "1d3be4c23a1534fe771742eb7d66b20309de9c6a6d28cc8e4728dfe9cea4b7eba1f14b1c6aea27469df086eb4acadc6a092afb376ca7689ecf7bf2d3c6fcfc75",
          "sha256": "d18ba34f174aafd8ac66b70be190af6f5aa8d8ce3c6e3c45f5b09c732095a38c",
          "sha1": "42ae5fc16e387d2f62971d12c707a15b43c30f1e",
          "md5": "2253806f40e4907722a4529ada97f93d"
        }
      ]
    }
  ]
}
