{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.10.0.aar",
          "url": "FluctSDK-9.10.0.aar",
          "size": 467744,
          "sha512": "b4da022cbaff6631254f33998116b0ce292d376bf2b845e875519aee46848850172612bbefd79deb04e97aee8d79b99d07c0142d4fedf5206dbdb7161b7f899d",
          "sha256": "54c8531b0ad22bfba767565afb62f52925a38c22481884273e2dd67b64a68987",
          "sha1": "c54b313f82b5e66523812585f60b9eae7a8ee507",
          "md5": "fe125b64e2cad2276a88fcd26eb95865"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.10.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.10.0.aar",
          "url": "FluctSDK-9.10.0.aar",
          "size": 467744,
          "sha512": "b4da022cbaff6631254f33998116b0ce292d376bf2b845e875519aee46848850172612bbefd79deb04e97aee8d79b99d07c0142d4fedf5206dbdb7161b7f899d",
          "sha256": "54c8531b0ad22bfba767565afb62f52925a38c22481884273e2dd67b64a68987",
          "sha1": "c54b313f82b5e66523812585f60b9eae7a8ee507",
          "md5": "fe125b64e2cad2276a88fcd26eb95865"
        }
      ]
    }
  ]
}
