{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.gma",
    "module": "gma-mediation",
    "version": "9.13.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "minimumReleaseVariantMinimumReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.14]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.13.14]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.13.14.aar",
          "url": "gma-mediation-9.13.14.aar",
          "size": 50802,
          "sha512": "47f2662de6517d0658902349fc8145198dffd0cbbef878ec1a9e98875f97ffa031096ba8fb118001edd42d43e1928a092ff08eb124552c5e352f00e972701816",
          "sha256": "c03df33cdc2ea745114644d65d6a3c06ae84c0ec22826961f02a8c9a0d6c9a66",
          "sha1": "71daaeeab6d04127d4e4bfb8bf4b5113414414b5",
          "md5": "5223b4b32f9c046d12c446b09c53b90d"
        }
      ]
    },
    {
      "name": "minimumReleaseVariantMinimumReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.14]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.13.14]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.13.14.aar",
          "url": "gma-mediation-9.13.14.aar",
          "size": 50802,
          "sha512": "47f2662de6517d0658902349fc8145198dffd0cbbef878ec1a9e98875f97ffa031096ba8fb118001edd42d43e1928a092ff08eb124552c5e352f00e972701816",
          "sha256": "c03df33cdc2ea745114644d65d6a3c06ae84c0ec22826961f02a8c9a0d6c9a66",
          "sha1": "71daaeeab6d04127d4e4bfb8bf4b5113414414b5",
          "md5": "5223b4b32f9c046d12c446b09c53b90d"
        }
      ]
    }
  ]
}
