{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "9.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "12.1.0"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.2]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.9.2.aar",
          "url": "applovin-adapter-9.9.2.aar",
          "size": 13605,
          "sha512": "2f34fc3325997f5ec8f8d090646bda9f2cfc10ef84d14f38bd2b1c59c1fb26b51a9c618f5949868aaeb00ae079ad00a27003915f03eca910515728d687bafc3e",
          "sha256": "a1f39448d15122210a9334e9b5db5b696339ecb50dee0ec7262e4960bd026ff7",
          "sha1": "6ef82392530d5afce08dc9ed56079047d8cbc0b4",
          "md5": "fc6ee8385dcb3f8ec4bb5f2d0a879ce6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "12.1.0"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.2]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.9.2"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.9.2.aar",
          "url": "applovin-adapter-9.9.2.aar",
          "size": 13605,
          "sha512": "2f34fc3325997f5ec8f8d090646bda9f2cfc10ef84d14f38bd2b1c59c1fb26b51a9c618f5949868aaeb00ae079ad00a27003915f03eca910515728d687bafc3e",
          "sha256": "a1f39448d15122210a9334e9b5db5b696339ecb50dee0ec7262e4960bd026ff7",
          "sha1": "6ef82392530d5afce08dc9ed56079047d8cbc0b4",
          "md5": "fc6ee8385dcb3f8ec4bb5f2d0a879ce6"
        }
      ]
    }
  ]
}
