{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.16.0]"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.16.0.aar",
          "url": "FluctSDK-9.16.0.aar",
          "size": 458136,
          "sha512": "7db2337c7604754ec06f698b6775ea9c5c279683f67a06a455fcfcd8f3aac44636c72c7c8f40797850851e050884972b657235c699e250abd518664bfe0f1942",
          "sha256": "ceec050f16aeae810b6620a35eda32953367238ff54cc7cf795d3a6721f803dd",
          "sha1": "c135cd58f03797448318965500edd5d7ac8f38e6",
          "md5": "6b7c3d72560cf8e4a7f335c623bc0a67"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.16.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.16.0]"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.16.0.aar",
          "url": "FluctSDK-9.16.0.aar",
          "size": 458136,
          "sha512": "7db2337c7604754ec06f698b6775ea9c5c279683f67a06a455fcfcd8f3aac44636c72c7c8f40797850851e050884972b657235c699e250abd518664bfe0f1942",
          "sha256": "ceec050f16aeae810b6620a35eda32953367238ff54cc7cf795d3a6721f803dd",
          "sha1": "c135cd58f03797448318965500edd5d7ac8f38e6",
          "md5": "6b7c3d72560cf8e4a7f335c623bc0a67"
        }
      ]
    }
  ]
}
