{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.12.2.aar",
          "url": "FluctSDK-9.12.2.aar",
          "size": 469649,
          "sha512": "5fd132f10c342ea9e633f5e6e43a4a7e0943d20cae65f02e7f2725fb6b61ef4e3c9dafee83b158c13b66ed386a911ba4bbda3144f3e82d1c01d7e3b238a0ff37",
          "sha256": "6830a5ad491adcd439786d4cbbdad1cd0b5e9084e6b32ca0e7c992278a702728",
          "sha1": "5cd64957be6878a2398884e1df5020b9bad0083b",
          "md5": "2c05ce45ea4f085dbc33bb435d8340b0"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.12.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.12.2.aar",
          "url": "FluctSDK-9.12.2.aar",
          "size": 469649,
          "sha512": "5fd132f10c342ea9e633f5e6e43a4a7e0943d20cae65f02e7f2725fb6b61ef4e3c9dafee83b158c13b66ed386a911ba4bbda3144f3e82d1c01d7e3b238a0ff37",
          "sha256": "6830a5ad491adcd439786d4cbbdad1cd0b5e9084e6b32ca0e7c992278a702728",
          "sha1": "5cd64957be6878a2398884e1df5020b9bad0083b",
          "md5": "2c05ce45ea4f085dbc33bb435d8340b0"
        }
      ]
    }
  ]
}
