{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.gma",
    "module": "gma-mediation",
    "version": "9.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "minimumReleaseVariantMinimumReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.2]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.15.2]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "nativead-core",
          "version": {
            "requires": "[9.15.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.15.2.aar",
          "url": "gma-mediation-9.15.2.aar",
          "size": 64523,
          "sha512": "756e0d66197670c8767b0cb662825a547f8bdd5d601fdb4576a022d7d632be658df86aba94c5ac402d09e7a30a130c5522ae8e9c121912c5161e9add2b27ea99",
          "sha256": "8e53049a3b67f5ee1f8b59372f433c073d27ac4f225fe32476dcb4d017f72de0",
          "sha1": "9f86cf56fbd93a5c99d02b06d074e51669b64fcc",
          "md5": "070c621c0edeebdb98114eec984715ab"
        }
      ]
    },
    {
      "name": "minimumReleaseVariantMinimumReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "23.1.0"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.2]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.15.2]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "nativead-core",
          "version": {
            "requires": "[9.15.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.15.2.aar",
          "url": "gma-mediation-9.15.2.aar",
          "size": 64523,
          "sha512": "756e0d66197670c8767b0cb662825a547f8bdd5d601fdb4576a022d7d632be658df86aba94c5ac402d09e7a30a130c5522ae8e9c121912c5161e9add2b27ea99",
          "sha256": "8e53049a3b67f5ee1f8b59372f433c073d27ac4f225fe32476dcb4d017f72de0",
          "sha1": "9f86cf56fbd93a5c99d02b06d074e51669b64fcc",
          "md5": "070c621c0edeebdb98114eec984715ab"
        }
      ]
    }
  ]
}
