{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation",
    "module": "rewardedvideo-mediation-nend",
    "version": "9.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.4.6]"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-nend-9.4.6.aar",
          "url": "rewardedvideo-mediation-nend-9.4.6.aar",
          "size": 31220,
          "sha512": "8bb0aed78a709002517e5ca812abecbde2e917709d0a6428041515d88e82feb4982dbea2426eddd71542e277d6933d05daa0ec700b28fea18265043e7be67d41",
          "sha256": "8d207f694a9885d4af8b8ab1dd3ce2d14d90f67614192c47ca529b8e344cb9de",
          "sha1": "0a83d603e5c11be5d782ee223a8f25f61ed70f0f",
          "md5": "4c72f5adde8fc01edd7c4522978434b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.4.6]"
          }
        },
        {
          "group": "net.nend.android",
          "module": "nend-sdk",
          "version": {
            "requires": "9.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-nend-9.4.6.aar",
          "url": "rewardedvideo-mediation-nend-9.4.6.aar",
          "size": 31220,
          "sha512": "8bb0aed78a709002517e5ca812abecbde2e917709d0a6428041515d88e82feb4982dbea2426eddd71542e277d6933d05daa0ec700b28fea18265043e7be67d41",
          "sha256": "8d207f694a9885d4af8b8ab1dd3ce2d14d90f67614192c47ca529b8e344cb9de",
          "sha1": "0a83d603e5c11be5d782ee223a8f25f61ed70f0f",
          "md5": "4c72f5adde8fc01edd7c4522978434b8"
        }
      ]
    }
  ]
}
