{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "9.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "11.5.1"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.6.1]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.6.1.aar",
          "url": "applovin-adapter-9.6.1.aar",
          "size": 13485,
          "sha512": "20665b8716cc16d18f62012f4a107e3e9fb9ca1507b2554946c0be0510bd37512aa2644cad92715bd581d2e9866e486d865a71e5b89a93a53a9645521e03cf8a",
          "sha256": "5e81479e2aadc7ac70e8c3afe27229b95d5c4bb77edf501f3386cc5e54b56d4a",
          "sha1": "1fcf97a2174f25fe25009e9dcbb5932c294ff2f3",
          "md5": "3e8872c558f425ebf7f3ae63d509d33b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "11.5.1"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.6.1]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.6.1.aar",
          "url": "applovin-adapter-9.6.1.aar",
          "size": 13485,
          "sha512": "20665b8716cc16d18f62012f4a107e3e9fb9ca1507b2554946c0be0510bd37512aa2644cad92715bd581d2e9866e486d865a71e5b89a93a53a9645521e03cf8a",
          "sha256": "5e81479e2aadc7ac70e8c3afe27229b95d5c4bb77edf501f3386cc5e54b56d4a",
          "sha1": "1fcf97a2174f25fe25009e9dcbb5932c294ff2f3",
          "md5": "3e8872c558f425ebf7f3ae63d509d33b"
        }
      ]
    }
  ]
}
