{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.13.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.6]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.6.aar",
          "url": "fullscreen-ads-9.13.6.aar",
          "size": 143519,
          "sha512": "6e7c80f480f7fd86771c97091b82e65acf1adee1c496ba6d68371d6cce5710fc15ac413b1beb11ddb2b49eac9588ad98b016efe8fd7c47023bc319225787caeb",
          "sha256": "b3f83be8750754acaf888ab4fb58aa784569ecb7744449017e110cb4231d5482",
          "sha1": "f6cab75faf6f9a9a08c59bf2d7fdd895efab4f82",
          "md5": "993f84eca923560b1934fcc515ae7c2d"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.6]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.6.aar",
          "url": "fullscreen-ads-9.13.6.aar",
          "size": 143519,
          "sha512": "6e7c80f480f7fd86771c97091b82e65acf1adee1c496ba6d68371d6cce5710fc15ac413b1beb11ddb2b49eac9588ad98b016efe8fd7c47023bc319225787caeb",
          "sha256": "b3f83be8750754acaf888ab4fb58aa784569ecb7744449017e110cb4231d5482",
          "sha1": "f6cab75faf6f9a9a08c59bf2d7fdd895efab4f82",
          "md5": "993f84eca923560b1934fcc515ae7c2d"
        }
      ]
    }
  ]
}
