{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.11.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.11.2.aar",
          "url": "FluctSDK-9.11.2.aar",
          "size": 468642,
          "sha512": "d3b7aa10c842e845d8516f663c1425e9efb5b4ce4f92cbd012f751fe23256e6c36387215d22fafced290b82d67086542141ae25c9a6369e9177a04a2d9827d64",
          "sha256": "5c0d2d9c614d1ba82d619eecfb69f2c092235ee8d0031b8b0397437c44b6b21e",
          "sha1": "35901eb5dfb5d51bbea2ed261f3348215a648bc4",
          "md5": "22fbfbf13586becda60e8ae0a1798449"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.11.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.11.2.aar",
          "url": "FluctSDK-9.11.2.aar",
          "size": 468642,
          "sha512": "d3b7aa10c842e845d8516f663c1425e9efb5b4ce4f92cbd012f751fe23256e6c36387215d22fafced290b82d67086542141ae25c9a6369e9177a04a2d9827d64",
          "sha256": "5c0d2d9c614d1ba82d619eecfb69f2c092235ee8d0031b8b0397437c44b6b21e",
          "sha1": "35901eb5dfb5d51bbea2ed261f3348215a648bc4",
          "md5": "22fbfbf13586becda60e8ae0a1798449"
        }
      ]
    }
  ]
}
