{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "9.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "minimumReleaseVariantMinimumReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.10.0]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.10.0"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "12.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.10.0.aar",
          "url": "applovin-adapter-9.10.0.aar",
          "size": 11826,
          "sha512": "67c7d4ea0d69af5518addd9ccc93aa0c414967ad8dc4db604181e848a376929c8bb78dfc2cb6b01d05a865cb34ae52cf069318d2c50e6339073dbf493df6b653",
          "sha256": "bac3b508d143160142b842e0864c15aab6e4ce1fe45fa4af4f35a47f8a3731e2",
          "sha1": "c9c168c8a1468ee34f442c768a34ef5fdc85799e",
          "md5": "bf40c5aef14aaafd588b6b13b9179803"
        }
      ]
    },
    {
      "name": "minimumReleaseVariantMinimumReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.10.0]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.10.0"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "12.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.10.0.aar",
          "url": "applovin-adapter-9.10.0.aar",
          "size": 11826,
          "sha512": "67c7d4ea0d69af5518addd9ccc93aa0c414967ad8dc4db604181e848a376929c8bb78dfc2cb6b01d05a865cb34ae52cf069318d2c50e6339073dbf493df6b653",
          "sha256": "bac3b508d143160142b842e0864c15aab6e4ce1fe45fa4af4f35a47f8a3731e2",
          "sha1": "c9c168c8a1468ee34f442c768a34ef5fdc85799e",
          "md5": "bf40c5aef14aaafd588b6b13b9179803"
        }
      ]
    }
  ]
}
