{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.6.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.6.2.aar",
          "url": "FluctSDK-9.6.2.aar",
          "size": 455316,
          "sha512": "ca713c47844f4a5e69f26c8012d57bc2994973bae13eabe0bef668884c8582ea810ff923929add391eed517e081ce28c50c7bc95bafecbc9dde26be470d8a00e",
          "sha256": "625d6caea40902ef1c072f7fcb6226fd538dd25220d79344966614caa77994d2",
          "sha1": "c0d9fb43db1aac98b3c1b33480c8e6a2555c7f3f",
          "md5": "6c657bc11b82f4c79e965cc55b199cd3"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.6.2]"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.6.2.aar",
          "url": "FluctSDK-9.6.2.aar",
          "size": 455316,
          "sha512": "ca713c47844f4a5e69f26c8012d57bc2994973bae13eabe0bef668884c8582ea810ff923929add391eed517e081ce28c50c7bc95bafecbc9dde26be470d8a00e",
          "sha256": "625d6caea40902ef1c072f7fcb6226fd538dd25220d79344966614caa77994d2",
          "sha1": "c0d9fb43db1aac98b3c1b33480c8e6a2555c7f3f",
          "md5": "6c657bc11b82f4c79e965cc55b199cd3"
        }
      ]
    }
  ]
}
