{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.gma",
    "module": "gma-mediation",
    "version": "9.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.6.3]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.6.3]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.6.3.aar",
          "url": "gma-mediation-9.6.3.aar",
          "size": 50164,
          "sha512": "1894af0b1b97246cd9f111a8add56170e265715fbf7e8070075330ea8eb4549f00a05c57f7692868d26ee64e56515f1418dff64a3e7308c18b891a5dd73e5737",
          "sha256": "ccd8022036fc08548a82f5471eb6151693205ed92e215a590395c23634aefd8a",
          "sha1": "d6bf51ff3ced40f474cb098aa6e4484ad9c9002d",
          "md5": "9842eddcffa2ee26f0927f2291d06fe6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.6.3]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.6.3]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.6.3.aar",
          "url": "gma-mediation-9.6.3.aar",
          "size": 50164,
          "sha512": "1894af0b1b97246cd9f111a8add56170e265715fbf7e8070075330ea8eb4549f00a05c57f7692868d26ee64e56515f1418dff64a3e7308c18b891a5dd73e5737",
          "sha256": "ccd8022036fc08548a82f5471eb6151693205ed92e215a590395c23634aefd8a",
          "sha1": "d6bf51ff3ced40f474cb098aa6e4484ad9c9002d",
          "md5": "9842eddcffa2ee26f0927f2291d06fe6"
        }
      ]
    }
  ]
}
