{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.8.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.8.2.aar",
          "url": "FluctSDK-9.8.2.aar",
          "size": 453832,
          "sha512": "b2955b11633c75b779c68d53b7528b03334df431a0e0ecefc01bc5d287ff0a6764c1934438a5cedee467a8b640d917eac368ecc3fc333070e9275453292805a4",
          "sha256": "fe321689f1ce04597b7aa06748fdfae905ebde34e2704b27f29fdaa5588d247a",
          "sha1": "711e5e546e998321dcdbc0f206a0a8b742fe8bdb",
          "md5": "4deb9ebaf013d8b312d3344865e8cdc7"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.8.2]"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.8.2.aar",
          "url": "FluctSDK-9.8.2.aar",
          "size": 453832,
          "sha512": "b2955b11633c75b779c68d53b7528b03334df431a0e0ecefc01bc5d287ff0a6764c1934438a5cedee467a8b640d917eac368ecc3fc333070e9275453292805a4",
          "sha256": "fe321689f1ce04597b7aa06748fdfae905ebde34e2704b27f29fdaa5588d247a",
          "sha1": "711e5e546e998321dcdbc0f206a0a8b742fe8bdb",
          "md5": "4deb9ebaf013d8b312d3344865e8cdc7"
        }
      ]
    }
  ]
}
