{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "vqhvyevfzrdd5lgm6ol37n4dzy"
    }
  },
  "variants": [
    {
      "name": "productionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.0.0.aar",
          "url": "FluctSDK-9.0.0.aar",
          "size": 585890,
          "sha512": "e56625a339aaa469705812749854427a7b7dd09722de2cd0026fc5579a6dbebe3142dcc63dbfc21584d89bdbbf1e18a765e91360141a2d660af04691b31dabee",
          "sha256": "61c4a36d24101ab426a63697a19c7ac0192cb3e578eba31c8b39b0ae286c5bf2",
          "sha1": "da7403b99248f009098b36ade249ffa603045a71",
          "md5": "6d1c2e3fac5277e1cc8042572ff1d4d0"
        }
      ]
    },
    {
      "name": "productionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "9.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.0.0.aar",
          "url": "FluctSDK-9.0.0.aar",
          "size": 585890,
          "sha512": "e56625a339aaa469705812749854427a7b7dd09722de2cd0026fc5579a6dbebe3142dcc63dbfc21584d89bdbbf1e18a765e91360141a2d660af04691b31dabee",
          "sha256": "61c4a36d24101ab426a63697a19c7ac0192cb3e578eba31c8b39b0ae286c5bf2",
          "sha1": "da7403b99248f009098b36ade249ffa603045a71",
          "md5": "6d1c2e3fac5277e1cc8042572ff1d4d0"
        }
      ]
    }
  ]
}
