{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "8.12.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "6zhos5l3erd5lk72fm32vsdv6y"
    }
  },
  "variants": [
    {
      "name": "productionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "FluctSDK-8.12.2.aar",
          "url": "FluctSDK-8.12.2.aar",
          "size": 580115,
          "sha512": "3e8084e44d7bf60373f55a132e9d7d7d32137babd30d1c552eee2a5956107732e0681b39ab26bf81ce287dfb8b6d9ff41287e4d699d5d4989682563e5ba37c61",
          "sha256": "d352abbef9ba79c1345a2317fe552425076547afeff6d1224ee45f751b19f736",
          "sha1": "5f9058516c40e27e2d87ddab807cb31431007435",
          "md5": "478a2ecd2ea3bff06fd6af1b8799ef50"
        }
      ]
    },
    {
      "name": "productionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-v4",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "webkit",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "8.12.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-8.12.2.aar",
          "url": "FluctSDK-8.12.2.aar",
          "size": 580115,
          "sha512": "3e8084e44d7bf60373f55a132e9d7d7d32137babd30d1c552eee2a5956107732e0681b39ab26bf81ce287dfb8b6d9ff41287e4d699d5d4989682563e5ba37c61",
          "sha256": "d352abbef9ba79c1345a2317fe552425076547afeff6d1224ee45f751b19f736",
          "sha1": "5f9058516c40e27e2d87ddab807cb31431007435",
          "md5": "478a2ecd2ea3bff06fd6af1b8799ef50"
        }
      ]
    }
  ]
}
