{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.12.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.12.1.aar",
          "url": "fullscreen-ads-9.12.1.aar",
          "size": 144233,
          "sha512": "798915b27733902845f4243cdb9d26c9f3eb4e4b0f724204377ab7d87379142a9d63a255abc49b51f73bdaf6a38275a7814d41b1e869456dd617ffdb3b73f889",
          "sha256": "37c3725699f1dd90b89ab1279956b81a1cbb41eed584a6c93e313bab6cf9f42e",
          "sha1": "b3e1475809ddb89bdf9fc4bda5feec16b188e68e",
          "md5": "78328885f103ce035c328e8b90ed3482"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.12.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.12.1.aar",
          "url": "fullscreen-ads-9.12.1.aar",
          "size": 144233,
          "sha512": "798915b27733902845f4243cdb9d26c9f3eb4e4b0f724204377ab7d87379142a9d63a255abc49b51f73bdaf6a38275a7814d41b1e869456dd617ffdb3b73f889",
          "sha256": "37c3725699f1dd90b89ab1279956b81a1cbb41eed584a6c93e313bab6cf9f42e",
          "sha1": "b3e1475809ddb89bdf9fc4bda5feec16b188e68e",
          "md5": "78328885f103ce035c328e8b90ed3482"
        }
      ]
    }
  ]
}
