{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.13.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.10]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.10.aar",
          "url": "fullscreen-ads-9.13.10.aar",
          "size": 143521,
          "sha512": "396202da2cff8f933cb6ddeea4b7b4a201c7746112769955fadec231995434a523fb02d1215f63f38f9893606bc610c1896b4467356ed35efb2ab83b74276e18",
          "sha256": "befe20e4f757df28e6752c33ec8cdc0def9912ea7a13708dc664bc965e08f361",
          "sha1": "f8bfc5e18712e3ef3aaaa0e4f6423e010f780579",
          "md5": "8611ebe724e9751e695d46a362edc439"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.10]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.10.aar",
          "url": "fullscreen-ads-9.13.10.aar",
          "size": 143521,
          "sha512": "396202da2cff8f933cb6ddeea4b7b4a201c7746112769955fadec231995434a523fb02d1215f63f38f9893606bc610c1896b4467356ed35efb2ab83b74276e18",
          "sha256": "befe20e4f757df28e6752c33ec8cdc0def9912ea7a13708dc664bc965e08f361",
          "sha1": "f8bfc5e18712e3ef3aaaa0e4f6423e010f780579",
          "md5": "8611ebe724e9751e695d46a362edc439"
        }
      ]
    }
  ]
}
