{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.3.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.3.1.aar",
          "url": "fullscreen-ads-9.3.1.aar",
          "size": 124003,
          "sha512": "1399d255a000c68f2d4b7e40b5dab7ff293acf4385e1a8c83bdfe2b25853e4880f14ce31c8fb4bde58673142466c8d53308bff261d7b6f0e5aeb172f495af88d",
          "sha256": "5cd2df2dccbc7f59f2c201d008aca1ae89d7333fe0fc9323c58cf32d35f66a87",
          "sha1": "b395f8adf4f1edf10670e67b3e79278b691284b4",
          "md5": "633b8d34e575d3a6d79cb95064755001"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.3.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "strictly": "[2.15.0,)",
            "requires": "[2.15.0,)",
            "prefers": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "strictly": "[2.15.0,)",
            "requires": "[2.15.0,)",
            "prefers": "2.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.3.1.aar",
          "url": "fullscreen-ads-9.3.1.aar",
          "size": 124003,
          "sha512": "1399d255a000c68f2d4b7e40b5dab7ff293acf4385e1a8c83bdfe2b25853e4880f14ce31c8fb4bde58673142466c8d53308bff261d7b6f0e5aeb172f495af88d",
          "sha256": "5cd2df2dccbc7f59f2c201d008aca1ae89d7333fe0fc9323c58cf32d35f66a87",
          "sha1": "b395f8adf4f1edf10670e67b3e79278b691284b4",
          "md5": "633b8d34e575d3a6d79cb95064755001"
        }
      ]
    }
  ]
}
