{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.12.1.aar",
          "url": "FluctSDK-9.12.1.aar",
          "size": 469650,
          "sha512": "704397da0bde7d0c4349a3db891b8ae78dcc353463fa13ddfcd20d2d768180e9433ca13b51d0d5dc2e8dc95aea74da05bf70333efb7a74354cce1910467f49d8",
          "sha256": "be16dca1b43615b9167ba8098290c80a76f969b7d819f4b13c0e18db60bb8a29",
          "sha1": "3ed46093db99b45f3676a3ac4dc87006bbc775d7",
          "md5": "d946392c20125c5dbc42158a31b4af4e"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.12.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.12.1.aar",
          "url": "FluctSDK-9.12.1.aar",
          "size": 469650,
          "sha512": "704397da0bde7d0c4349a3db891b8ae78dcc353463fa13ddfcd20d2d768180e9433ca13b51d0d5dc2e8dc95aea74da05bf70333efb7a74354cce1910467f49d8",
          "sha256": "be16dca1b43615b9167ba8098290c80a76f969b7d819f4b13c0e18db60bb8a29",
          "sha1": "3ed46093db99b45f3676a3ac4dc87006bbc775d7",
          "md5": "d946392c20125c5dbc42158a31b4af4e"
        }
      ]
    }
  ]
}
