{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.9.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.12]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.9.12.aar",
          "url": "fullscreen-ads-9.9.12.aar",
          "size": 144236,
          "sha512": "ba7df3504878a77fc1e027a79c9d07d4ceccfc54e35d6b1311a28ee24b4cd4a0daca03a74b341c1e566b2c5c927ff73ada0c71f391ee15d3172635d01e247e2a",
          "sha256": "58792d74aa254282729027135643f874c288e07b00e163ea74224da155b19648",
          "sha1": "1ba647c5582a550844ae8f2d1cebc912eeb42771",
          "md5": "9f10c96e258bf8f611385f422952a0c9"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.12]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.9.12.aar",
          "url": "fullscreen-ads-9.9.12.aar",
          "size": 144236,
          "sha512": "ba7df3504878a77fc1e027a79c9d07d4ceccfc54e35d6b1311a28ee24b4cd4a0daca03a74b341c1e566b2c5c927ff73ada0c71f391ee15d3172635d01e247e2a",
          "sha256": "58792d74aa254282729027135643f874c288e07b00e163ea74224da155b19648",
          "sha1": "1ba647c5582a550844ae8f2d1cebc912eeb42771",
          "md5": "9f10c96e258bf8f611385f422952a0c9"
        }
      ]
    }
  ]
}
