{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.13.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.4.aar",
          "url": "FluctSDK-9.13.4.aar",
          "size": 490306,
          "sha512": "83939956586ec3eb337427d3dbb3a01e2c8df1b32e4f15a72932f4e4ab1c191b390bee9b2ad22dfb9b0b6d692731d7ad59e2f0377fd80da480cc08b35c0d07c0",
          "sha256": "68f497b00f325ce7203ea21b7d406eb7110eabc03be933e6482594cb5b17da64",
          "sha1": "391b7c0983d8f142a1f79a7739b807a6d69eb59d",
          "md5": "35eb45c5f4d341944eb476b7d76a0c69"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.13.4]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.4.aar",
          "url": "FluctSDK-9.13.4.aar",
          "size": 490306,
          "sha512": "83939956586ec3eb337427d3dbb3a01e2c8df1b32e4f15a72932f4e4ab1c191b390bee9b2ad22dfb9b0b6d692731d7ad59e2f0377fd80da480cc08b35c0d07c0",
          "sha256": "68f497b00f325ce7203ea21b7d406eb7110eabc03be933e6482594cb5b17da64",
          "sha1": "391b7c0983d8f142a1f79a7739b807a6d69eb59d",
          "md5": "35eb45c5f4d341944eb476b7d76a0c69"
        }
      ]
    }
  ]
}
