{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.15.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.15.0.aar",
          "url": "FluctSDK-9.15.0.aar",
          "size": 477842,
          "sha512": "c9a6e1539c1b2140f2759248fe6e00b373c2ca82237008a2b8ce262b7b565ff1671b2848584edc87a4205254a91e30c045b91418e5713ba5220ff3d79d32a54e",
          "sha256": "fa0dbd01504d17472ce04c998973708a424ebccec1dfcd1ef443425a83537e67",
          "sha1": "3cf967ff93a24bfe0b5626ccbd58e686ea5ec0b3",
          "md5": "4ccadbb2e4a6972eb7e90be4312e9e0a"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.15.0]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.15.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.15.0.aar",
          "url": "FluctSDK-9.15.0.aar",
          "size": 477842,
          "sha512": "c9a6e1539c1b2140f2759248fe6e00b373c2ca82237008a2b8ce262b7b565ff1671b2848584edc87a4205254a91e30c045b91418e5713ba5220ff3d79d32a54e",
          "sha256": "fa0dbd01504d17472ce04c998973708a424ebccec1dfcd1ef443425a83537e67",
          "sha1": "3cf967ff93a24bfe0b5626ccbd58e686ea5ec0b3",
          "md5": "4ccadbb2e4a6972eb7e90be4312e9e0a"
        }
      ]
    }
  ]
}
