{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "8.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "strictly": "[11.0.0,)",
            "requires": "[11.0.0,)",
            "prefers": "11.3.3"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "8.14.0",
            "prefers": "8.14.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "8.14.0",
            "prefers": "8.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-8.14.0.aar",
          "url": "applovin-adapter-8.14.0.aar",
          "size": 13122,
          "sha512": "1e9075e036c3aa746655ec6e5958a2e70a0791d3540f0c1e74114170583808c860e48d908f1a9e92a61e1f8a39656e12259c393b5337c274837fc317fd95a0ad",
          "sha256": "fd45acca3f874da3c820d83168394d3054ef6e8e715fdd1160fec756cfcbf86b",
          "sha1": "33401ec2337e0e36f410ca9b1187e91ab3c8e1f8",
          "md5": "12c251dc9067d2385fa82d8dd770e52a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "strictly": "[11.0.0,)",
            "requires": "[11.0.0,)",
            "prefers": "11.3.3"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "8.14.0",
            "prefers": "8.14.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "8.14.0",
            "prefers": "8.14.0"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-8.14.0.aar",
          "url": "applovin-adapter-8.14.0.aar",
          "size": 13122,
          "sha512": "1e9075e036c3aa746655ec6e5958a2e70a0791d3540f0c1e74114170583808c860e48d908f1a9e92a61e1f8a39656e12259c393b5337c274837fc317fd95a0ad",
          "sha256": "fd45acca3f874da3c820d83168394d3054ef6e8e715fdd1160fec756cfcbf86b",
          "sha1": "33401ec2337e0e36f410ca9b1187e91ab3c8e1f8",
          "md5": "12c251dc9067d2385fa82d8dd770e52a"
        }
      ]
    }
  ]
}
