{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.4.7]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.4.7.aar",
          "url": "fullscreen-ads-9.4.7.aar",
          "size": 119017,
          "sha512": "84ff8c3722f571781b4ece0f7a30e27f0560dae961ec6f7096a2e770b8a3cb8cc822fc230c3fb100ce7676269a19a347d1ce4a60d058a92b663aa1f9c5bdeb2f",
          "sha256": "3701d5678b19f44d8c109cb63a09127c26d1afc55a3ac5b93466fb97b1079395",
          "sha1": "35dde0e1aa309285b4e579a66794058650b4334b",
          "md5": "15bb5fdc3621b898e232253802fadb8f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.4.7]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.4.7.aar",
          "url": "fullscreen-ads-9.4.7.aar",
          "size": 119017,
          "sha512": "84ff8c3722f571781b4ece0f7a30e27f0560dae961ec6f7096a2e770b8a3cb8cc822fc230c3fb100ce7676269a19a347d1ce4a60d058a92b663aa1f9c5bdeb2f",
          "sha256": "3701d5678b19f44d8c109cb63a09127c26d1afc55a3ac5b93466fb97b1079395",
          "sha1": "35dde0e1aa309285b4e579a66794058650b4334b",
          "md5": "15bb5fdc3621b898e232253802fadb8f"
        }
      ]
    }
  ]
}
