{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.4.4.aar",
          "url": "FluctSDK-9.4.4.aar",
          "size": 451597,
          "sha512": "e5d880150e26022d25c0a7fb8664fee2c7f20a859a9bf7a2991b363a137204ab5545b9e2d8855a6eb8691cf45cedd36b5efb884735dc864486edf816b58f7dfc",
          "sha256": "0553c46768e8aa128a19aa1c38f6d4835664674e1056546c5be87628a94152f2",
          "sha1": "c12ee5b350e0a82229bce9bc59d40375e5cd6543",
          "md5": "c9dbe3a5083930164a89ff9ab901efad"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "9.4.4"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.4.4.aar",
          "url": "FluctSDK-9.4.4.aar",
          "size": 451597,
          "sha512": "e5d880150e26022d25c0a7fb8664fee2c7f20a859a9bf7a2991b363a137204ab5545b9e2d8855a6eb8691cf45cedd36b5efb884735dc864486edf816b58f7dfc",
          "sha256": "0553c46768e8aa128a19aa1c38f6d4835664674e1056546c5be87628a94152f2",
          "sha1": "c12ee5b350e0a82229bce9bc59d40375e5cd6543",
          "md5": "c9dbe3a5083930164a89ff9ab901efad"
        }
      ]
    }
  ]
}
