{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.6.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.6.3]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.6.3.aar",
          "url": "fullscreen-ads-9.6.3.aar",
          "size": 142688,
          "sha512": "5d94cb361c837210716b86877413aa6cf36e4b9be15f74f52b2af7c470d1d590e237f393faab94f86bc67de7e7118932fbc97a685eac91761d50ba266002f8e3",
          "sha256": "e5223bba101a0aeb507e4da5741f4b3fe42f63b7b7b221f59e49c1b4c23cad2d",
          "sha1": "a813bbe4ad7d595b8859f439c5a786ffd143856d",
          "md5": "3a38b991dffb4c733ff877afdd14605e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.6.3]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.6.3.aar",
          "url": "fullscreen-ads-9.6.3.aar",
          "size": 142688,
          "sha512": "5d94cb361c837210716b86877413aa6cf36e4b9be15f74f52b2af7c470d1d590e237f393faab94f86bc67de7e7118932fbc97a685eac91761d50ba266002f8e3",
          "sha256": "e5223bba101a0aeb507e4da5741f4b3fe42f63b7b7b221f59e49c1b4c23cad2d",
          "sha1": "a813bbe4ad7d595b8859f439c5a786ffd143856d",
          "md5": "3a38b991dffb4c733ff877afdd14605e"
        }
      ]
    }
  ]
}
