{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.4.0.aar",
          "url": "FluctSDK-9.4.0.aar",
          "size": 574262,
          "sha512": "84ed86d825aa3f2f50d02c0ee8266c9a0a82171c440e6394a4622c45f49aaac0165a9b6505433303256c70ad874da04fc31325915ead51b9e85d3a2750a2b030",
          "sha256": "cf4a5a17ee4227b5392d93e2075b7c688dd973cdb08b2c27ba690f6c23204abe",
          "sha1": "65cda67ba883431bee5e96812a5f078766b8b57c",
          "md5": "296b63a3ea46c10df306efcf34c49942"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "9.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.4.0.aar",
          "url": "FluctSDK-9.4.0.aar",
          "size": 574262,
          "sha512": "84ed86d825aa3f2f50d02c0ee8266c9a0a82171c440e6394a4622c45f49aaac0165a9b6505433303256c70ad874da04fc31325915ead51b9e85d3a2750a2b030",
          "sha256": "cf4a5a17ee4227b5392d93e2075b7c688dd973cdb08b2c27ba690f6c23204abe",
          "sha1": "65cda67ba883431bee5e96812a5f078766b8b57c",
          "md5": "296b63a3ea46c10df306efcf34c49942"
        }
      ]
    }
  ]
}
