{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.4.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.4.2.aar",
          "url": "fullscreen-ads-9.4.2.aar",
          "size": 123996,
          "sha512": "cc5f8ff4fdff1dae8adeb909e659840eb7a68a07ca656518085d9f0bf1d2b39d3fbbc3e416f76b68d37b7125cef642d53d7d1a834ffa2b5d56f8897bd8e5d93d",
          "sha256": "811b21965966eab76b7d50f4bcf1b025bd57eb0b806d722d77552d1f4adb91fe",
          "sha1": "ed029423b9905d2ff7b9f8ffcf68e6f915c14a71",
          "md5": "ed36241d98911c4841081607fd0b5ab8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.4.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "strictly": "[2.15.0,)",
            "requires": "[2.15.0,)",
            "prefers": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "strictly": "[2.15.0,)",
            "requires": "[2.15.0,)",
            "prefers": "2.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.4.2.aar",
          "url": "fullscreen-ads-9.4.2.aar",
          "size": 123996,
          "sha512": "cc5f8ff4fdff1dae8adeb909e659840eb7a68a07ca656518085d9f0bf1d2b39d3fbbc3e416f76b68d37b7125cef642d53d7d1a834ffa2b5d56f8897bd8e5d93d",
          "sha256": "811b21965966eab76b7d50f4bcf1b025bd57eb0b806d722d77552d1f4adb91fe",
          "sha1": "ed029423b9905d2ff7b9f8ffcf68e6f915c14a71",
          "md5": "ed36241d98911c4841081607fd0b5ab8"
        }
      ]
    }
  ]
}
