{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.9.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.11.aar",
          "url": "FluctSDK-9.9.11.aar",
          "size": 457700,
          "sha512": "f716b9a867eeb0f8fff0af824a003e0479eb6a2d39cbf1f12eca4da11455c8bf07a1d5f51186f1f4bced02c56872a728dbfee54809db2dba4fc3bf4186891444",
          "sha256": "44ec47971290d16482c6c974359a1b8c0db0b996bd685ba65840f162295cba74",
          "sha1": "85acf19cb7609df4a5bcafb5e91127467fec0baf",
          "md5": "72957b37603d0331fad0afbfb122da0e"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.9.11]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.11.aar",
          "url": "FluctSDK-9.9.11.aar",
          "size": 457700,
          "sha512": "f716b9a867eeb0f8fff0af824a003e0479eb6a2d39cbf1f12eca4da11455c8bf07a1d5f51186f1f4bced02c56872a728dbfee54809db2dba4fc3bf4186891444",
          "sha256": "44ec47971290d16482c6c974359a1b8c0db0b996bd685ba65840f162295cba74",
          "sha1": "85acf19cb7609df4a5bcafb5e91127467fec0baf",
          "md5": "72957b37603d0331fad0afbfb122da0e"
        }
      ]
    }
  ]
}
