{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "tjri5ti7lvh53fv5puz4tmq4ma"
    }
  },
  "variants": [
    {
      "name": "productionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.0.2.aar",
          "url": "FluctSDK-9.0.2.aar",
          "size": 586343,
          "sha512": "d87e822a153734d13e314ca45ce67cbd8b274722b44ec1e2af6e4cd5e1a4f6052928f3ae80a13a6233b29dff4c50a52a31e857df51d1d37a65275d7e263ad712",
          "sha256": "2f65e2d6bd69af3b836e1e7589acd74db653ab2243cb848c51dfa7713c5ca306",
          "sha1": "7b19ae5034741a60a5584ef48cbe59edff0737ce",
          "md5": "2451064a5c94df22eb481a3ac30412cd"
        }
      ]
    },
    {
      "name": "productionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "9.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.0.2.aar",
          "url": "FluctSDK-9.0.2.aar",
          "size": 586343,
          "sha512": "d87e822a153734d13e314ca45ce67cbd8b274722b44ec1e2af6e4cd5e1a4f6052928f3ae80a13a6233b29dff4c50a52a31e857df51d1d37a65275d7e263ad712",
          "sha256": "2f65e2d6bd69af3b836e1e7589acd74db653ab2243cb848c51dfa7713c5ca306",
          "sha1": "7b19ae5034741a60a5584ef48cbe59edff0737ce",
          "md5": "2451064a5c94df22eb481a3ac30412cd"
        }
      ]
    }
  ]
}
