{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.3]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.15.3.aar",
          "url": "fullscreen-ads-9.15.3.aar",
          "size": 145904,
          "sha512": "ea2ad723a81f7c52095211be611d85c945fbcccb4a8b04fef28cdc8c78131bd964f3d74267081fa0679a131499ac179c00c1be5d058d8df9ade705943a05401f",
          "sha256": "c105eae2385bbfea365bf73bb552d6faad50f736faac4fa837b7cf56ab90188c",
          "sha1": "d963f6811d8840956723ae47e3b459a3a8cb4076",
          "md5": "7b33518db16d19ca24888e0883f9ae80"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.15.3]"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.3]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.15.3.aar",
          "url": "fullscreen-ads-9.15.3.aar",
          "size": 145904,
          "sha512": "ea2ad723a81f7c52095211be611d85c945fbcccb4a8b04fef28cdc8c78131bd964f3d74267081fa0679a131499ac179c00c1be5d058d8df9ade705943a05401f",
          "sha256": "c105eae2385bbfea365bf73bb552d6faad50f736faac4fa837b7cf56ab90188c",
          "sha1": "d963f6811d8840956723ae47e3b459a3a8cb4076",
          "md5": "7b33518db16d19ca24888e0883f9ae80"
        }
      ]
    }
  ]
}
