{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "9.9.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.11]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.9.11"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.9.11.aar",
          "url": "applovin-adapter-9.9.11.aar",
          "size": 12184,
          "sha512": "0f4f48e5b84f17e8a988c3f2ffb1499a6192736258c4e69bc46923d61430fcd54b39277e313e1d2d5e1bbe4f892f808f32d04fc6dff3a15957f6bb132b6046ce",
          "sha256": "151fd39282303cf0e1102ccfafdc44b810cff42803386296c9251964effdfd1c",
          "sha1": "996a680c45d47df5f06d72d41f3bba6c2d35603c",
          "md5": "bbaf276d38fdbe3a6528c4e363525f03"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "12.3.1"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.11]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.9.11"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.9.11.aar",
          "url": "applovin-adapter-9.9.11.aar",
          "size": 12184,
          "sha512": "0f4f48e5b84f17e8a988c3f2ffb1499a6192736258c4e69bc46923d61430fcd54b39277e313e1d2d5e1bbe4f892f808f32d04fc6dff3a15957f6bb132b6046ce",
          "sha256": "151fd39282303cf0e1102ccfafdc44b810cff42803386296c9251964effdfd1c",
          "sha1": "996a680c45d47df5f06d72d41f3bba6c2d35603c",
          "md5": "bbaf276d38fdbe3a6528c4e363525f03"
        }
      ]
    }
  ]
}
