{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "yexmv76bavdqljjemd3m567muq"
    }
  },
  "variants": [
    {
      "name": "productionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.1.0.aar",
          "url": "FluctSDK-9.1.0.aar",
          "size": 588717,
          "sha512": "1c283118962a5d6979d427e402274549226ed3fda322b54050d69a4187ed8776fde493deae3cefeb4ad0a486225b1c8ddd25afdf424ea6c0b663ae0c5be1db76",
          "sha256": "188265d9bad131b18438d5afc28a7949fee8c47ee4fa46fbbe7a0dc52b132beb",
          "sha1": "b4938528e75783724947a91ab6abd6baefe804f0",
          "md5": "98d83655aad91a1ef22d047cf6cb45b5"
        }
      ]
    },
    {
      "name": "productionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "9.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.1.0.aar",
          "url": "FluctSDK-9.1.0.aar",
          "size": 588717,
          "sha512": "1c283118962a5d6979d427e402274549226ed3fda322b54050d69a4187ed8776fde493deae3cefeb4ad0a486225b1c8ddd25afdf424ea6c0b663ae0c5be1db76",
          "sha256": "188265d9bad131b18438d5afc28a7949fee8c47ee4fa46fbbe7a0dc52b132beb",
          "sha1": "b4938528e75783724947a91ab6abd6baefe804f0",
          "md5": "98d83655aad91a1ef22d047cf6cb45b5"
        }
      ]
    }
  ]
}
