{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "8.14.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "strictly": "[11.0.0,)",
            "requires": "[11.0.0,)",
            "prefers": "11.3.3"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "8.14.1",
            "prefers": "8.14.1"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "8.14.1",
            "prefers": "8.14.1"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-8.14.1.aar",
          "url": "applovin-adapter-8.14.1.aar",
          "size": 13163,
          "sha512": "bcbc4bd6de8a254ddfbd755818cf396df6a51ab1d98f672c1e78d74da71467b0468b6a3f01ec3ed78a11123e2bcf411f82614a26975ee4909525ae38e3f42c19",
          "sha256": "99fc3809bb341c335f1548c6193b7f79fcac6e9f81785caf572744e255c19f82",
          "sha1": "f69525deba4b742b7f019ba452c3302a7a1a8d8d",
          "md5": "40234909c5d988d3bc5226a4baeeaac8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "strictly": "[11.0.0,)",
            "requires": "[11.0.0,)",
            "prefers": "11.3.3"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "8.14.1",
            "prefers": "8.14.1"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "8.14.1",
            "prefers": "8.14.1"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-8.14.1.aar",
          "url": "applovin-adapter-8.14.1.aar",
          "size": 13163,
          "sha512": "bcbc4bd6de8a254ddfbd755818cf396df6a51ab1d98f672c1e78d74da71467b0468b6a3f01ec3ed78a11123e2bcf411f82614a26975ee4909525ae38e3f42c19",
          "sha256": "99fc3809bb341c335f1548c6193b7f79fcac6e9f81785caf572744e255c19f82",
          "sha1": "f69525deba4b742b7f019ba452c3302a7a1a8d8d",
          "md5": "40234909c5d988d3bc5226a4baeeaac8"
        }
      ]
    }
  ]
}
