{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.8.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.8.4.aar",
          "url": "FluctSDK-9.8.4.aar",
          "size": 453847,
          "sha512": "4db89c9c0e3835e776235d19e329cc5fca4892c8726366a0feb8deade5bfad9f5b7169d1cbce94570cac5fb5cab3567b5cd812a517a5706bb36545a8ff3f2d81",
          "sha256": "816c30bcdd2fa632e2c58eac7c39b534197fe991c4a999412106661cf758bc73",
          "sha1": "c923583c051fbb34e66f3d646b4235ab09d8ed6f",
          "md5": "74bc24bed3c758800f8f19f8694daa09"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.8.4]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.8.4.aar",
          "url": "FluctSDK-9.8.4.aar",
          "size": 453847,
          "sha512": "4db89c9c0e3835e776235d19e329cc5fca4892c8726366a0feb8deade5bfad9f5b7169d1cbce94570cac5fb5cab3567b5cd812a517a5706bb36545a8ff3f2d81",
          "sha256": "816c30bcdd2fa632e2c58eac7c39b534197fe991c4a999412106661cf758bc73",
          "sha1": "c923583c051fbb34e66f3d646b4235ab09d8ed6f",
          "md5": "74bc24bed3c758800f8f19f8694daa09"
        }
      ]
    }
  ]
}
