{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.9.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.7.aar",
          "url": "FluctSDK-9.9.7.aar",
          "size": 455639,
          "sha512": "1370fd921f5645b07b1215932b55bcac9b80811904bc6d713a3807cada196b0675f8e98d427f3150e3182f746fdc5097a1059f2c886d0b6c90c1ad041859d296",
          "sha256": "ac3d238862cf75eca4ee4aa5f61d03905fe4ba52449c49eef90bef72d94a10ad",
          "sha1": "1896ac95514e0779ad21cd98f84e7a3b5259fad5",
          "md5": "df0c18f47819a19ae931a27499100e17"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.9.7]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.7.aar",
          "url": "FluctSDK-9.9.7.aar",
          "size": 455639,
          "sha512": "1370fd921f5645b07b1215932b55bcac9b80811904bc6d713a3807cada196b0675f8e98d427f3150e3182f746fdc5097a1059f2c886d0b6c90c1ad041859d296",
          "sha256": "ac3d238862cf75eca4ee4aa5f61d03905fe4ba52449c49eef90bef72d94a10ad",
          "sha1": "1896ac95514e0779ad21cd98f84e7a3b5259fad5",
          "md5": "df0c18f47819a19ae931a27499100e17"
        }
      ]
    }
  ]
}
