{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.0.aar",
          "url": "FluctSDK-9.9.0.aar",
          "size": 455993,
          "sha512": "bf2d66425ac2f7be3975263d3271ef5a45071f289cb2147a7baa01494632c06a30d2c8be82a82e014d766b3bbe1a1d48c46e14f397f6ffd95595948af14a438a",
          "sha256": "dfed09eb0dda12c45bad2a7a702cadb2ae67dda9f3b4207c85cb7fe72a29f0af",
          "sha1": "fbe5824630050b8cc66613468c67d607ee27ea2e",
          "md5": "a2633fe3524665f2c64918a4fd16fce3"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.9.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.0.aar",
          "url": "FluctSDK-9.9.0.aar",
          "size": 455993,
          "sha512": "bf2d66425ac2f7be3975263d3271ef5a45071f289cb2147a7baa01494632c06a30d2c8be82a82e014d766b3bbe1a1d48c46e14f397f6ffd95595948af14a438a",
          "sha256": "dfed09eb0dda12c45bad2a7a702cadb2ae67dda9f3b4207c85cb7fe72a29f0af",
          "sha1": "fbe5824630050b8cc66613468c67d607ee27ea2e",
          "md5": "a2633fe3524665f2c64918a4fd16fce3"
        }
      ]
    }
  ]
}
