{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.10.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.10.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.10.0.aar",
          "url": "fullscreen-ads-9.10.0.aar",
          "size": 144243,
          "sha512": "c48757a32377168db810bf8fd48335e9487b4dfc21ccab69dee431b6adf44ec12dbfa0300372561341950902521ae1c76bbaf5a76adfabb55212b5db5c89dcc3",
          "sha256": "a3e8b592fd8fb04fe028b828985d7b6240dba5423515bf52553e432359b224e8",
          "sha1": "8a7ccb4928a5fff2a0327f760284832dde431084",
          "md5": "1643da8dc376cdbbdfe004a2ba6c8670"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.10.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.10.0.aar",
          "url": "fullscreen-ads-9.10.0.aar",
          "size": 144243,
          "sha512": "c48757a32377168db810bf8fd48335e9487b4dfc21ccab69dee431b6adf44ec12dbfa0300372561341950902521ae1c76bbaf5a76adfabb55212b5db5c89dcc3",
          "sha256": "a3e8b592fd8fb04fe028b828985d7b6240dba5423515bf52553e432359b224e8",
          "sha1": "8a7ccb4928a5fff2a0327f760284832dde431084",
          "md5": "1643da8dc376cdbbdfe004a2ba6c8670"
        }
      ]
    }
  ]
}
