{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.gma",
    "module": "gma-mediation",
    "version": "8.12.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ox5bsvc7pjegflq5bdhwg5rchi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "17.2.0"
          },
          "excludes": [
            {
              "group": "com.android.support",
              "module": "support-annotations"
            }
          ]
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[8.12.4]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[8.12.4]"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-8.12.4.aar",
          "url": "gma-mediation-8.12.4.aar",
          "size": 42728,
          "sha512": "a13186b092c857c24e5fa622d1babc97a67386a6d07e4f7b949b0343c2fd824fc59960d5fc609421bf97dd680f6da10669f370cdb52ed0185eed72618add2112",
          "sha256": "35325b941939c5e2f9bb30d104f981122183125d68dcd5cc30ce651a21cb66d3",
          "sha1": "282e6fd176b193d131013e445ee571b07f7dc0ab",
          "md5": "8c3a42f987e4b87d06d049908a06283b"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[8.12.4]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[8.12.4]"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-8.12.4.aar",
          "url": "gma-mediation-8.12.4.aar",
          "size": 42728,
          "sha512": "a13186b092c857c24e5fa622d1babc97a67386a6d07e4f7b949b0343c2fd824fc59960d5fc609421bf97dd680f6da10669f370cdb52ed0185eed72618add2112",
          "sha256": "35325b941939c5e2f9bb30d104f981122183125d68dcd5cc30ce651a21cb66d3",
          "sha1": "282e6fd176b193d131013e445ee571b07f7dc0ab",
          "md5": "8c3a42f987e4b87d06d049908a06283b"
        }
      ]
    }
  ]
}
