{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "nativead-core",
    "version": "9.15.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "nativead-core-9.15.3.aar",
          "url": "nativead-core-9.15.3.aar",
          "size": 96383,
          "sha512": "da0107ffb308cafcd0e3247682ec4c3a9457654eecaafc26e9cb5f04442c6a4d35176504e4ccfc55a0044cf69e8828efbc6f1e8035d47089479ae06393e48b3b",
          "sha256": "e0521e895c111170c44a179c6f170960e1896e51502e50449dc581263e6d0b9c",
          "sha1": "a6ff6a75f7ea3d78f83c3dd1e11fb4aa39bb1602",
          "md5": "f1fd4e013e91de6e48cb82d57d2f16de"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.15.3]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.15.3]"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "nativead-core-9.15.3.aar",
          "url": "nativead-core-9.15.3.aar",
          "size": 96383,
          "sha512": "da0107ffb308cafcd0e3247682ec4c3a9457654eecaafc26e9cb5f04442c6a4d35176504e4ccfc55a0044cf69e8828efbc6f1e8035d47089479ae06393e48b3b",
          "sha256": "e0521e895c111170c44a179c6f170960e1896e51502e50449dc581263e6d0b9c",
          "sha1": "a6ff6a75f7ea3d78f83c3dd1e11fb4aa39bb1602",
          "md5": "f1fd4e013e91de6e48cb82d57d2f16de"
        }
      ]
    }
  ]
}
