{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.9.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.9.0.aar",
          "url": "fullscreen-ads-9.9.0.aar",
          "size": 143816,
          "sha512": "c234311b9766ca048d15d83255a52901456270770dc2ab5018a2c4b830dd5f9c728c1be05e095400fc19dc07d14dc35ee88cfa3c67d9bdac59ca9fd5a2987db5",
          "sha256": "dd8afae047b14b1de5216ed0795c6b8f1d53a2e16f96e140ad8732576c562787",
          "sha1": "ddc8ac920c51ac62b3df8c8d1f337d2880509fe9",
          "md5": "f6410a07d823e5076f74e682a845a3de"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.9.0.aar",
          "url": "fullscreen-ads-9.9.0.aar",
          "size": 143816,
          "sha512": "c234311b9766ca048d15d83255a52901456270770dc2ab5018a2c4b830dd5f9c728c1be05e095400fc19dc07d14dc35ee88cfa3c67d9bdac59ca9fd5a2987db5",
          "sha256": "dd8afae047b14b1de5216ed0795c6b8f1d53a2e16f96e140ad8732576c562787",
          "sha1": "ddc8ac920c51ac62b3df8c8d1f337d2880509fe9",
          "md5": "f6410a07d823e5076f74e682a845a3de"
        }
      ]
    }
  ]
}
