{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation",
    "module": "videointerstitial-mediation-adcolony",
    "version": "9.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "fgt4uplg65hglah2i25rvydjti"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.1.1]"
          }
        }
      ],
      "files": [
        {
          "name": "videointerstitial-mediation-adcolony-9.1.1.aar",
          "url": "videointerstitial-mediation-adcolony-9.1.1.aar",
          "size": 16870,
          "sha512": "75ca66ad5ef436098b70485e7654889a288b428903f0e725fe726bfa8c964bce89d147db3c0f7dbc9e8670ee2c42a21ab4d425d2ce9a4438321c8f87d6707e74",
          "sha256": "9fbc7f171b32d4c656b1371dad00a8cceafa1b2c839d6f72d695e4e4d9452ef8",
          "sha1": "c2792812aab7b405f95ac71526def9f5db9a1f92",
          "md5": "100f2b74a590a224df6c96fbd377ff3b"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.1.1]"
          }
        },
        {
          "group": "jp.fluct.mediation",
          "module": "rewardedvideo-mediation-adcolony",
          "version": {
            "requires": "9.1.1"
          }
        }
      ],
      "files": [
        {
          "name": "videointerstitial-mediation-adcolony-9.1.1.aar",
          "url": "videointerstitial-mediation-adcolony-9.1.1.aar",
          "size": 16870,
          "sha512": "75ca66ad5ef436098b70485e7654889a288b428903f0e725fe726bfa8c964bce89d147db3c0f7dbc9e8670ee2c42a21ab4d425d2ce9a4438321c8f87d6707e74",
          "sha256": "9fbc7f171b32d4c656b1371dad00a8cceafa1b2c839d6f72d695e4e4d9452ef8",
          "sha1": "c2792812aab7b405f95ac71526def9f5db9a1f92",
          "md5": "100f2b74a590a224df6c96fbd377ff3b"
        }
      ]
    }
  ]
}
