{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.9.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.5.aar",
          "url": "FluctSDK-9.9.5.aar",
          "size": 455640,
          "sha512": "4ce410e43f1ddda6043e10a5ec660f7d9f85ca347f6c9e0b94aa42d0e711257dd1df4efedba4f817fcf477d6ae7ccaa95c45c75e1e867654fc90d80efac1ee21",
          "sha256": "d3824bf83f40d14cc0f32d248a247db8fb6913418ae11a02a1bbbc82c070d441",
          "sha1": "5331ed30b152e1e829e4e6752ec44e597cce4ac0",
          "md5": "0d843f15315988326f94946530db6a1e"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.9.5]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.5.aar",
          "url": "FluctSDK-9.9.5.aar",
          "size": 455640,
          "sha512": "4ce410e43f1ddda6043e10a5ec660f7d9f85ca347f6c9e0b94aa42d0e711257dd1df4efedba4f817fcf477d6ae7ccaa95c45c75e1e867654fc90d80efac1ee21",
          "sha256": "d3824bf83f40d14cc0f32d248a247db8fb6913418ae11a02a1bbbc82c070d441",
          "sha1": "5331ed30b152e1e829e4e6752ec44e597cce4ac0",
          "md5": "0d843f15315988326f94946530db6a1e"
        }
      ]
    }
  ]
}
