{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "nativead-core",
    "version": "9.15.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "nativead-core-9.15.5.aar",
          "url": "nativead-core-9.15.5.aar",
          "size": 101744,
          "sha512": "e134a7e47272f06caadf04f598adde86ef8607561d0afa0f95e276d91b47ef0df298c835b6557b10a07172afdf793a2741386d0a1b091b33e526f49a00336c3a",
          "sha256": "e6e40f551305032e5b8f4102e4e217d0c14a2f87bb6f210986252075d54ea2b6",
          "sha1": "204949e6821408a2fbe42b397797dd00d3581423",
          "md5": "da343759fa8aca81999efdabbba357f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.15.5]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.15.5]"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "nativead-core-9.15.5.aar",
          "url": "nativead-core-9.15.5.aar",
          "size": 101744,
          "sha512": "e134a7e47272f06caadf04f598adde86ef8607561d0afa0f95e276d91b47ef0df298c835b6557b10a07172afdf793a2741386d0a1b091b33e526f49a00336c3a",
          "sha256": "e6e40f551305032e5b8f4102e4e217d0c14a2f87bb6f210986252075d54ea2b6",
          "sha1": "204949e6821408a2fbe42b397797dd00d3581423",
          "md5": "da343759fa8aca81999efdabbba357f3"
        }
      ]
    }
  ]
}
