{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation",
    "module": "rewardedvideo-mediation-applovin",
    "version": "9.13.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "applovinDefaultReleaseVariantApplovinDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.4]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-applovin-9.13.4.aar",
          "url": "rewardedvideo-mediation-applovin-9.13.4.aar",
          "size": 23397,
          "sha512": "e165f45d0eacb4c585d373f16293841c00f7633d5a82af6f409d7cec38f42ffc7296d9dcf8c4cb2246699b77368120de5e2f33d0966a01c24a2e964124e09afe",
          "sha256": "0092c818f1e93bfbfad1a3e4950c83e73e16b4956529e2b3f4578248d48ab6d5",
          "sha1": "bfb96ae01868b92ff2bb039fafd3eba52801018f",
          "md5": "bfd2d5fb08832788d1b96f2d85d150e7"
        }
      ]
    },
    {
      "name": "applovinDefaultReleaseVariantApplovinDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.1.0"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.4]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-applovin-9.13.4.aar",
          "url": "rewardedvideo-mediation-applovin-9.13.4.aar",
          "size": 23397,
          "sha512": "e165f45d0eacb4c585d373f16293841c00f7633d5a82af6f409d7cec38f42ffc7296d9dcf8c4cb2246699b77368120de5e2f33d0966a01c24a2e964124e09afe",
          "sha256": "0092c818f1e93bfbfad1a3e4950c83e73e16b4956529e2b3f4578248d48ab6d5",
          "sha1": "bfb96ae01868b92ff2bb039fafd3eba52801018f",
          "md5": "bfd2d5fb08832788d1b96f2d85d150e7"
        }
      ]
    }
  ]
}
