{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation",
    "module": "rewardedvideo-mediation-amoad",
    "version": "9.11.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.11.0]"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-amoad-9.11.0.aar",
          "url": "rewardedvideo-mediation-amoad-9.11.0.aar",
          "size": 29117,
          "sha512": "320fcc1c6316c6993f511a975f76ac2343b34633aa8698495a642c6560d0d8af9e97ec008dcd7e9f19a5f1a6dfad1372c1efbaf90cf4f1795127689b3c197e83",
          "sha256": "b0a6fc64182b17401f06c34de6ef9ac68e5841619ed6ddd8c52e505b0c8e0d2c",
          "sha1": "0d57d597c96546d608deca54d420da5a3269a008",
          "md5": "32ec1201b73822303fb5c83d8e49499f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.amoad",
          "module": "amoad-sdk",
          "version": {
            "requires": "5.2.26"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.11.0]"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-amoad-9.11.0.aar",
          "url": "rewardedvideo-mediation-amoad-9.11.0.aar",
          "size": 29117,
          "sha512": "320fcc1c6316c6993f511a975f76ac2343b34633aa8698495a642c6560d0d8af9e97ec008dcd7e9f19a5f1a6dfad1372c1efbaf90cf4f1795127689b3c197e83",
          "sha256": "b0a6fc64182b17401f06c34de6ef9ac68e5841619ed6ddd8c52e505b0c8e0d2c",
          "sha1": "0d57d597c96546d608deca54d420da5a3269a008",
          "md5": "32ec1201b73822303fb5c83d8e49499f"
        }
      ]
    }
  ]
}
