{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.8.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.8.9.aar",
          "url": "FluctSDK-9.8.9.aar",
          "size": 454076,
          "sha512": "b5bf62cf9d81d3bbafe2e204df7721af6540b4e448305c016eed39be38521932d4e302ef78ce1891cc9a7692604295df194bfb14b706b72b55b02bfe8165f76b",
          "sha256": "dd2fdf045a6cfb09e549246b604881898e3a55435abb5ad6249625e0a01c3f6c",
          "sha1": "ffcd88b8df9880c59ede4a3fb8ba52af1c877cdc",
          "md5": "3803f88983c6f38af058db711f22295d"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.8.9]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.8.9.aar",
          "url": "FluctSDK-9.8.9.aar",
          "size": 454076,
          "sha512": "b5bf62cf9d81d3bbafe2e204df7721af6540b4e448305c016eed39be38521932d4e302ef78ce1891cc9a7692604295df194bfb14b706b72b55b02bfe8165f76b",
          "sha256": "dd2fdf045a6cfb09e549246b604881898e3a55435abb5ad6249625e0a01c3f6c",
          "sha1": "ffcd88b8df9880c59ede4a3fb8ba52af1c877cdc",
          "md5": "3803f88983c6f38af058db711f22295d"
        }
      ]
    }
  ]
}
