{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "nativead-core",
    "version": "9.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "nativead-core-9.15.2.aar",
          "url": "nativead-core-9.15.2.aar",
          "size": 95803,
          "sha512": "1ac6921921342f8eb9741a33741d28d83c47aaa049a7fc1d1810755192537b4cc8d1eecf42b28f69a7c8b0ce12305c074e9a82905a437f0714cd15a3f66dfc63",
          "sha256": "b5fbb318c373fcc7770a2afca556eef53328646eaf284274334f87620a2a360c",
          "sha1": "193665a3262e904d8e0c5c7b3a32bc87099e5482",
          "md5": "bcbf17428c99d54ae373ba5cd0e5038d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.15.2]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.15.2]"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "nativead-core-9.15.2.aar",
          "url": "nativead-core-9.15.2.aar",
          "size": 95803,
          "sha512": "1ac6921921342f8eb9741a33741d28d83c47aaa049a7fc1d1810755192537b4cc8d1eecf42b28f69a7c8b0ce12305c074e9a82905a437f0714cd15a3f66dfc63",
          "sha256": "b5fbb318c373fcc7770a2afca556eef53328646eaf284274334f87620a2a360c",
          "sha1": "193665a3262e904d8e0c5c7b3a32bc87099e5482",
          "md5": "bcbf17428c99d54ae373ba5cd0e5038d"
        }
      ]
    }
  ]
}
