{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.9.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.10.aar",
          "url": "FluctSDK-9.9.10.aar",
          "size": 458147,
          "sha512": "02ab8baf563cff16112921b44b2e75592f0d046805c5c9931ae25070e32a2629878143898189ea4ae69bc112fc4094d0c2dc2a2c5406abe522e17c5b395abc9d",
          "sha256": "eeabc2507772ed327f50c404bad7cdda79ade99614e4b81271d9e0fbb832b5c2",
          "sha1": "128eadf573ba95ea4da21b3365b8d1f0cd8eed9a",
          "md5": "6418dae3565adc1f5bb4cd849f4c3804"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.9.10]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.10.aar",
          "url": "FluctSDK-9.9.10.aar",
          "size": 458147,
          "sha512": "02ab8baf563cff16112921b44b2e75592f0d046805c5c9931ae25070e32a2629878143898189ea4ae69bc112fc4094d0c2dc2a2c5406abe522e17c5b395abc9d",
          "sha256": "eeabc2507772ed327f50c404bad7cdda79ade99614e4b81271d9e0fbb832b5c2",
          "sha1": "128eadf573ba95ea4da21b3365b8d1f0cd8eed9a",
          "md5": "6418dae3565adc1f5bb4cd849f4c3804"
        }
      ]
    }
  ]
}
