{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "9.15.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "minimumReleaseVariantMinimumReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.4]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.15.4"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.15.4.aar",
          "url": "applovin-adapter-9.15.4.aar",
          "size": 19018,
          "sha512": "d99064cadcb36d86315fcb69eaae398bdafa8c613ff88ff6d96949875172d464054d9ced752e1c4542e56a5c9364748539516e30014c4cf1e5e7a13ecec8e4e5",
          "sha256": "5690afae22a628569da7258d6e6e6262379bf7c09dfeee3f2d8f717745215132",
          "sha1": "3384b9ea677947b380c6a3391dd267f78ab8f568",
          "md5": "e69d9b508d6d6c5115bb7aaaa4b6367c"
        }
      ]
    },
    {
      "name": "minimumReleaseVariantMinimumReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.4]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.15.4"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.15.4.aar",
          "url": "applovin-adapter-9.15.4.aar",
          "size": 19018,
          "sha512": "d99064cadcb36d86315fcb69eaae398bdafa8c613ff88ff6d96949875172d464054d9ced752e1c4542e56a5c9364748539516e30014c4cf1e5e7a13ecec8e4e5",
          "sha256": "5690afae22a628569da7258d6e6e6262379bf7c09dfeee3f2d8f717745215132",
          "sha1": "3384b9ea677947b380c6a3391dd267f78ab8f568",
          "md5": "e69d9b508d6d6c5115bb7aaaa4b6367c"
        }
      ]
    }
  ]
}
