{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.gma",
    "module": "gma-mediation",
    "version": "9.13.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "minimumReleaseVariantMinimumReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.0]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.13.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.13.0.aar",
          "url": "gma-mediation-9.13.0.aar",
          "size": 50205,
          "sha512": "d7229fccd44a08dcdb17c8ea170c87e68ae89dd1366420f8e4b6fcf3da6042fae3a17d7b41740a9388c635d387d74063d44653fc886afeead848c0df0ca13f15",
          "sha256": "c87d58aabc8b37b2b321a37a37e2238e2a3e624754cb642fe912529584a2df45",
          "sha1": "be9fca9967008f7a472f9319f038df0a3ab48e5f",
          "md5": "785c19f0e55499b77d488de3eb313308"
        }
      ]
    },
    {
      "name": "minimumReleaseVariantMinimumReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.0]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.13.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.13.0.aar",
          "url": "gma-mediation-9.13.0.aar",
          "size": 50205,
          "sha512": "d7229fccd44a08dcdb17c8ea170c87e68ae89dd1366420f8e4b6fcf3da6042fae3a17d7b41740a9388c635d387d74063d44653fc886afeead848c0df0ca13f15",
          "sha256": "c87d58aabc8b37b2b321a37a37e2238e2a3e624754cb642fe912529584a2df45",
          "sha1": "be9fca9967008f7a472f9319f038df0a3ab48e5f",
          "md5": "785c19f0e55499b77d488de3eb313308"
        }
      ]
    }
  ]
}
