{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation",
    "module": "rewardedvideo-mediation-unityads",
    "version": "9.9.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.5]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-unityads-9.9.5.aar",
          "url": "rewardedvideo-mediation-unityads-9.9.5.aar",
          "size": 28077,
          "sha512": "83054a3f978dc8dda9571ae482c0ee4faf4f3461d274623d42de7011e5777264e4c766d099585d16639e6374b0dfb75bdea9d1d0640bdb82a5a06ed2e2ff0759",
          "sha256": "30c4348a8aea6c7262d7e4dccca59c3d363a5ad07ae16e528fad680954636734",
          "sha1": "f36cda33377a569868b5a4f8b3daf9cd9b91f3fe",
          "md5": "fa3b7e327ba86494d65a997f9df171e0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.unity3d.ads",
          "module": "unity-ads",
          "version": {
            "requires": "4.9.3"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.5]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-unityads-9.9.5.aar",
          "url": "rewardedvideo-mediation-unityads-9.9.5.aar",
          "size": 28077,
          "sha512": "83054a3f978dc8dda9571ae482c0ee4faf4f3461d274623d42de7011e5777264e4c766d099585d16639e6374b0dfb75bdea9d1d0640bdb82a5a06ed2e2ff0759",
          "sha256": "30c4348a8aea6c7262d7e4dccca59c3d363a5ad07ae16e528fad680954636734",
          "sha1": "f36cda33377a569868b5a4f8b3daf9cd9b91f3fe",
          "md5": "fa3b7e327ba86494d65a997f9df171e0"
        }
      ]
    }
  ]
}
