{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.9.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.8.aar",
          "url": "FluctSDK-9.9.8.aar",
          "size": 458268,
          "sha512": "97963f00eb8b63f423eb60a96e29f0c35508c650faf848e9a50600ea8a1c3354d75e1e88400e083af550035c6517d8adfcef8fb84c518d90732b622b84f3626d",
          "sha256": "40c4aa91d20dfa30f82444e8d2986b49645a3357db8fea9a3cd5aee5925d77f1",
          "sha1": "df347e48af1ef462624571a6f29857fec1947be1",
          "md5": "ed673e35a946ffb2edb15909b22db841"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.9.8]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.8.aar",
          "url": "FluctSDK-9.9.8.aar",
          "size": 458268,
          "sha512": "97963f00eb8b63f423eb60a96e29f0c35508c650faf848e9a50600ea8a1c3354d75e1e88400e083af550035c6517d8adfcef8fb84c518d90732b622b84f3626d",
          "sha256": "40c4aa91d20dfa30f82444e8d2986b49645a3357db8fea9a3cd5aee5925d77f1",
          "sha1": "df347e48af1ef462624571a6f29857fec1947be1",
          "md5": "ed673e35a946ffb2edb15909b22db841"
        }
      ]
    }
  ]
}
