{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation",
    "module": "rewardedvideo-mediation-five",
    "version": "9.6.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.6.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-five-9.6.1.aar",
          "url": "rewardedvideo-mediation-five-9.6.1.aar",
          "size": 20790,
          "sha512": "fa9031e05c680457f989bcbe2fb5ce6d8f862b5a59661022e8aaa2ddb52a9d4f4febc49e8362cc1be313b76e23056da1e8c7bf67230f01c0df506a07c0e9f9f0",
          "sha256": "d79c5534f13091e973e34658c4e64b83c63eefc0181c95b4186f47eed4b4f608",
          "sha1": "235d2cfc43248d105caed4104c777942d7efc9e0",
          "md5": "2fd736488825acb3a49615a1927b8a3c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.6.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.linecorp.adsnetwork",
          "module": "fivead",
          "version": {
            "requires": "2.6.20230215"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-five-9.6.1.aar",
          "url": "rewardedvideo-mediation-five-9.6.1.aar",
          "size": 20790,
          "sha512": "fa9031e05c680457f989bcbe2fb5ce6d8f862b5a59661022e8aaa2ddb52a9d4f4febc49e8362cc1be313b76e23056da1e8c7bf67230f01c0df506a07c0e9f9f0",
          "sha256": "d79c5534f13091e973e34658c4e64b83c63eefc0181c95b4186f47eed4b4f608",
          "sha1": "235d2cfc43248d105caed4104c777942d7efc9e0",
          "md5": "2fd736488825acb3a49615a1927b8a3c"
        }
      ]
    }
  ]
}
