{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.13.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.10.aar",
          "url": "FluctSDK-9.13.10.aar",
          "size": 493941,
          "sha512": "b6cdc2fff286d7ae541552956d13728ba3ab53499cdc7e21d8e72008c861159e39f00d774a90f9ec65dcceeedd907721d4835f8d29ce7edb11d5c1b3588232f7",
          "sha256": "de05d2bc4c9f38ddc2f34fa0ddfe3f8d0782361739db76143dd4e0982c9ad262",
          "sha1": "f8e78fd40fb3f41c0f3b5a653e3494c644cfe9d0",
          "md5": "2c6fdca5691f8727e6c890fa37f235eb"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.13.10]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.10.aar",
          "url": "FluctSDK-9.13.10.aar",
          "size": 493941,
          "sha512": "b6cdc2fff286d7ae541552956d13728ba3ab53499cdc7e21d8e72008c861159e39f00d774a90f9ec65dcceeedd907721d4835f8d29ce7edb11d5c1b3588232f7",
          "sha256": "de05d2bc4c9f38ddc2f34fa0ddfe3f8d0782361739db76143dd4e0982c9ad262",
          "sha1": "f8e78fd40fb3f41c0f3b5a653e3494c644cfe9d0",
          "md5": "2c6fdca5691f8727e6c890fa37f235eb"
        }
      ]
    }
  ]
}
