{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.16.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.16.1.aar",
          "url": "fullscreen-ads-9.16.1.aar",
          "size": 146040,
          "sha512": "2ecd269d0a1c018a459cc797db1f0d70e53924659e7995d81141eb0ca7e9f6ad5f16a4e87891c3fd1e4a9c81ab3e8dc0421bae44f4d904442f1e503402d224d0",
          "sha256": "683ea03f307c495b684729b35a38f9d8e056cad5b6da6177c3493e8cd3107cf4",
          "sha1": "877bef3591a648cb19920d3c01d0d2eb7a78696d",
          "md5": "bd5fe61393c5bcb9f34851b349b462bd"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.16.1]"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.16.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.16.1.aar",
          "url": "fullscreen-ads-9.16.1.aar",
          "size": 146040,
          "sha512": "2ecd269d0a1c018a459cc797db1f0d70e53924659e7995d81141eb0ca7e9f6ad5f16a4e87891c3fd1e4a9c81ab3e8dc0421bae44f4d904442f1e503402d224d0",
          "sha256": "683ea03f307c495b684729b35a38f9d8e056cad5b6da6177c3493e8cd3107cf4",
          "sha1": "877bef3591a648cb19920d3c01d0d2eb7a78696d",
          "md5": "bd5fe61393c5bcb9f34851b349b462bd"
        }
      ]
    }
  ]
}
