{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "shared",
    "version": "9.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "shared-9.16.2.aar",
          "url": "shared-9.16.2.aar",
          "size": 82238,
          "sha512": "28e892fc6876f2a3a9f370f9d64ddc14a3cbd87bbefffc7865984f50345a9bca7d3f8f5fa6acce7da491c7e3c44db44e6f1c53089b03b3c51eab5e1c84f07980",
          "sha256": "6400849611d476184063c7ca70083ec475d8ee22eaaa8ec505c9d895a3c6ac3e",
          "sha1": "f51470c10a43765317dbce642ab827f9e932d4d6",
          "md5": "4d166c01d5b8a8005238af255e988dcc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "shared-9.16.2.aar",
          "url": "shared-9.16.2.aar",
          "size": 82238,
          "sha512": "28e892fc6876f2a3a9f370f9d64ddc14a3cbd87bbefffc7865984f50345a9bca7d3f8f5fa6acce7da491c7e3c44db44e6f1c53089b03b3c51eab5e1c84f07980",
          "sha256": "6400849611d476184063c7ca70083ec475d8ee22eaaa8ec505c9d895a3c6ac3e",
          "sha1": "f51470c10a43765317dbce642ab827f9e932d4d6",
          "md5": "4d166c01d5b8a8005238af255e988dcc"
        }
      ]
    }
  ]
}
