{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.15.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.15.2.aar",
          "url": "fullscreen-ads-9.15.2.aar",
          "size": 145900,
          "sha512": "77094fd7109b0773bf60b5f903af20575adbdc6c95f143071312ef6cb62444b11d42daa728cce0c596461fcc8fa867c09ed0648ab5b27a1ed16a155a1ac5f3d2",
          "sha256": "9796cb31c2572fc4cf9accb5039050305e58f2f254f22070db2596dc7db5c8a8",
          "sha1": "22ea07bf76e629ea46c24e5b7267e8436aedec61",
          "md5": "adf23951c9d14841d3fc402083e630a9"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.15.2]"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.15.2.aar",
          "url": "fullscreen-ads-9.15.2.aar",
          "size": 145900,
          "sha512": "77094fd7109b0773bf60b5f903af20575adbdc6c95f143071312ef6cb62444b11d42daa728cce0c596461fcc8fa867c09ed0648ab5b27a1ed16a155a1ac5f3d2",
          "sha256": "9796cb31c2572fc4cf9accb5039050305e58f2f254f22070db2596dc7db5c8a8",
          "sha1": "22ea07bf76e629ea46c24e5b7267e8436aedec61",
          "md5": "adf23951c9d14841d3fc402083e630a9"
        }
      ]
    }
  ]
}
