{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.2.aar",
          "url": "FluctSDK-9.13.2.aar",
          "size": 490046,
          "sha512": "8e55bef6ac826dde3548abae6c54c2c903f458326b8de2365d7a81342832b6e4c7582163a4cdb694dcb7c7a79145b6cd58f228870abbed6856512a56deb795a1",
          "sha256": "e041bd1f8428a338413297688ab82a6882b6cc0a7c8db6d4260c38eab985f434",
          "sha1": "360c001b5c68541fac0b2e0265d7234ae43bae65",
          "md5": "45564850d444daf379cb1f36ea6c974d"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.13.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.2.aar",
          "url": "FluctSDK-9.13.2.aar",
          "size": 490046,
          "sha512": "8e55bef6ac826dde3548abae6c54c2c903f458326b8de2365d7a81342832b6e4c7582163a4cdb694dcb7c7a79145b6cd58f228870abbed6856512a56deb795a1",
          "sha256": "e041bd1f8428a338413297688ab82a6882b6cc0a7c8db6d4260c38eab985f434",
          "sha1": "360c001b5c68541fac0b2e0265d7234ae43bae65",
          "md5": "45564850d444daf379cb1f36ea6c974d"
        }
      ]
    }
  ]
}
