{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.gma",
    "module": "gma-mediation",
    "version": "9.13.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "minimumReleaseVariantMinimumReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.12]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.13.12]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.13.12.aar",
          "url": "gma-mediation-9.13.12.aar",
          "size": 50804,
          "sha512": "2eb304ce2cec7840518cf61dbf8b7b0968520085176ab3ac813297301df76e7021882ba726bfa702391af2a0e83f2fdade3dcc891648e265631e60d6481eef48",
          "sha256": "7b798bfeb48d1606eff3a8d7f87d79b48a3bef0a2a1d8b9b44eab0d784cd8560",
          "sha1": "dba6189288a10f278b48c0e24c77b7fbbe9e2f21",
          "md5": "d8c5bfaddea9420cf9cc46df222089a8"
        }
      ]
    },
    {
      "name": "minimumReleaseVariantMinimumReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.12]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.13.12]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.13.12.aar",
          "url": "gma-mediation-9.13.12.aar",
          "size": 50804,
          "sha512": "2eb304ce2cec7840518cf61dbf8b7b0968520085176ab3ac813297301df76e7021882ba726bfa702391af2a0e83f2fdade3dcc891648e265631e60d6481eef48",
          "sha256": "7b798bfeb48d1606eff3a8d7f87d79b48a3bef0a2a1d8b9b44eab0d784cd8560",
          "sha1": "dba6189288a10f278b48c0e24c77b7fbbe9e2f21",
          "md5": "d8c5bfaddea9420cf9cc46df222089a8"
        }
      ]
    }
  ]
}
