{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.16.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.16.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.16.2.aar",
          "url": "fullscreen-ads-9.16.2.aar",
          "size": 146050,
          "sha512": "06d679b02da4c9ee7a9bb7f011c7378eefb6ac01974559c582231023e53ec2843949def7c84840bfab93a8b88dd2ca260ce3d68f38e6caa35d2d08326f465d4b",
          "sha256": "630b705035acc31b1be6716af814ea46499c8912cf576e1f1314970d5787e01f",
          "sha1": "23880291e135ae5691a3c60a8be77ccacc24e92c",
          "md5": "daa85bf335787173ce92dc0b263f575f"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.16.2]"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.16.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.16.2.aar",
          "url": "fullscreen-ads-9.16.2.aar",
          "size": 146050,
          "sha512": "06d679b02da4c9ee7a9bb7f011c7378eefb6ac01974559c582231023e53ec2843949def7c84840bfab93a8b88dd2ca260ce3d68f38e6caa35d2d08326f465d4b",
          "sha256": "630b705035acc31b1be6716af814ea46499c8912cf576e1f1314970d5787e01f",
          "sha1": "23880291e135ae5691a3c60a8be77ccacc24e92c",
          "md5": "daa85bf335787173ce92dc0b263f575f"
        }
      ]
    }
  ]
}
