{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.8.1.aar",
          "url": "fullscreen-ads-9.8.1.aar",
          "size": 142678,
          "sha512": "4b45e88ff5cfef8b83d830bdaf133fe855ab59f41f21258273de02f11d2a11043d9b4b5154843a81a4ca4de385f96b7f9bbbcf660c15fefaf7ff309b91fd11c0",
          "sha256": "65119a3df89bb22a582659ce48e0b78a929da6118cd18903d61066a1ff110f97",
          "sha1": "15eb28203d72489757c901df961c490b803bca32",
          "md5": "6d7f36dca86ff67184c24b233f16a0e9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.8.1.aar",
          "url": "fullscreen-ads-9.8.1.aar",
          "size": 142678,
          "sha512": "4b45e88ff5cfef8b83d830bdaf133fe855ab59f41f21258273de02f11d2a11043d9b4b5154843a81a4ca4de385f96b7f9bbbcf660c15fefaf7ff309b91fd11c0",
          "sha256": "65119a3df89bb22a582659ce48e0b78a929da6118cd18903d61066a1ff110f97",
          "sha1": "15eb28203d72489757c901df961c490b803bca32",
          "md5": "6d7f36dca86ff67184c24b233f16a0e9"
        }
      ]
    }
  ]
}
