{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.9.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.7]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.9.7.aar",
          "url": "fullscreen-ads-9.9.7.aar",
          "size": 143694,
          "sha512": "ec89ffd57b5b893dfd34b8588eade4a25f1ad6fc9390a37ca258ada22d21c7c17d1174458c5fa8a356d591ad01049d247b91f92a2915254cd20618bd39be85bd",
          "sha256": "c629014d022ca1e9695b2c111dbdd91d36fdda0685d1ab5eec9b29edade14539",
          "sha1": "827005ef29f7e411961bc4f21cb182502b7bdf5f",
          "md5": "6c726d079396fa0e16f925c1787eb54a"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.7]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.9.7.aar",
          "url": "fullscreen-ads-9.9.7.aar",
          "size": 143694,
          "sha512": "ec89ffd57b5b893dfd34b8588eade4a25f1ad6fc9390a37ca258ada22d21c7c17d1174458c5fa8a356d591ad01049d247b91f92a2915254cd20618bd39be85bd",
          "sha256": "c629014d022ca1e9695b2c111dbdd91d36fdda0685d1ab5eec9b29edade14539",
          "sha1": "827005ef29f7e411961bc4f21cb182502b7bdf5f",
          "md5": "6c726d079396fa0e16f925c1787eb54a"
        }
      ]
    }
  ]
}
