{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.3.aar",
          "url": "FluctSDK-9.9.3.aar",
          "size": 456266,
          "sha512": "c5ac9788949fd8e665777186938302e921cc5beadac952492d2c0363fc634c52905edd3c77b171970b30bdfb2e7c78038bee6a8ffdfa16e0209d7723b489cccd",
          "sha256": "d4379c828b377329fb5b58299988a0596a86c4f7be1749d6bbf236342078d187",
          "sha1": "8a33c58db0f3c9a66c69031f8126d0fbe3068eb0",
          "md5": "df352188442a2ddfc3cf439761d79648"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.9.3]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.3.aar",
          "url": "FluctSDK-9.9.3.aar",
          "size": 456266,
          "sha512": "c5ac9788949fd8e665777186938302e921cc5beadac952492d2c0363fc634c52905edd3c77b171970b30bdfb2e7c78038bee6a8ffdfa16e0209d7723b489cccd",
          "sha256": "d4379c828b377329fb5b58299988a0596a86c4f7be1749d6bbf236342078d187",
          "sha1": "8a33c58db0f3c9a66c69031f8126d0fbe3068eb0",
          "md5": "df352188442a2ddfc3cf439761d79648"
        }
      ]
    }
  ]
}
