{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.15.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.15.1.aar",
          "url": "fullscreen-ads-9.15.1.aar",
          "size": 145902,
          "sha512": "1ce7bf3c4896b75d50df7ea8c6f888a3214a97b576f22c876baf0c456639737d735d58eda496985d4d1e6e64308e2c4158f26bbe2ccf5a30fd623a7287cb85bb",
          "sha256": "3f146ad625cabe442a23f66cac1e8875dd8e31e0b3ca8ba8ef0bba337273fa57",
          "sha1": "1f91fc1ef23564bec7c4b3b6d34d2fb8711c4852",
          "md5": "d86beb2937e23077dd7c970a33bc26d2"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.15.1]"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.15.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.15.1.aar",
          "url": "fullscreen-ads-9.15.1.aar",
          "size": 145902,
          "sha512": "1ce7bf3c4896b75d50df7ea8c6f888a3214a97b576f22c876baf0c456639737d735d58eda496985d4d1e6e64308e2c4158f26bbe2ccf5a30fd623a7287cb85bb",
          "sha256": "3f146ad625cabe442a23f66cac1e8875dd8e31e0b3ca8ba8ef0bba337273fa57",
          "sha1": "1f91fc1ef23564bec7c4b3b6d34d2fb8711c4852",
          "md5": "d86beb2937e23077dd7c970a33bc26d2"
        }
      ]
    }
  ]
}
