{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation",
    "module": "rewardedvideo-mediation-amoad",
    "version": "9.4.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.4.5]"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-amoad-9.4.5.aar",
          "url": "rewardedvideo-mediation-amoad-9.4.5.aar",
          "size": 22103,
          "sha512": "163cc60f26a98325452fdb9d3717fe96cc52dab3fde5484b768f4006e6ef1090d8b3e3f18a1be8623c37cb4d8283595ccd7b8f26826e254f41bdaf2f4b2608a3",
          "sha256": "0b56ec2ffc4e1e5a66aae0bdafc4571bfa56510801506a3c6f68cb179ef95ec9",
          "sha1": "2645e353359089919149b3b17c739973d009282f",
          "md5": "9120c3c0118ff7e23bc06325f27f64ca"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.4.5]"
          }
        },
        {
          "group": "com.amoad",
          "module": "amoad-sdk",
          "version": {
            "requires": "5.2.18"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.localbroadcastmanager",
          "module": "localbroadcastmanager",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-amoad-9.4.5.aar",
          "url": "rewardedvideo-mediation-amoad-9.4.5.aar",
          "size": 22103,
          "sha512": "163cc60f26a98325452fdb9d3717fe96cc52dab3fde5484b768f4006e6ef1090d8b3e3f18a1be8623c37cb4d8283595ccd7b8f26826e254f41bdaf2f4b2608a3",
          "sha256": "0b56ec2ffc4e1e5a66aae0bdafc4571bfa56510801506a3c6f68cb179ef95ec9",
          "sha1": "2645e353359089919149b3b17c739973d009282f",
          "md5": "9120c3c0118ff7e23bc06325f27f64ca"
        }
      ]
    }
  ]
}
