{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.4.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.4.6.aar",
          "url": "FluctSDK-9.4.6.aar",
          "size": 449827,
          "sha512": "c78b2e686d5b9757582545a391bb16efedb3d5a5efda465f9e2fdbcf0b527074acd53ca35cad40cba159a659ff7e7f743323071aca2e1099b5aa31d9cb6f763a",
          "sha256": "e31c5413d7070f5548f1728f2b8b78285880e94eb0ca6d5bf770752649b8a13b",
          "sha1": "e1aa9cc2a27346c59201d1de2e6068f052ef3b67",
          "md5": "4813d98f78e9bdb7f0d4cb2f18a97441"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "9.4.6"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.4.6.aar",
          "url": "FluctSDK-9.4.6.aar",
          "size": 449827,
          "sha512": "c78b2e686d5b9757582545a391bb16efedb3d5a5efda465f9e2fdbcf0b527074acd53ca35cad40cba159a659ff7e7f743323071aca2e1099b5aa31d9cb6f763a",
          "sha256": "e31c5413d7070f5548f1728f2b8b78285880e94eb0ca6d5bf770752649b8a13b",
          "sha1": "e1aa9cc2a27346c59201d1de2e6068f052ef3b67",
          "md5": "4813d98f78e9bdb7f0d4cb2f18a97441"
        }
      ]
    }
  ]
}
