{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.12.0.aar",
          "url": "FluctSDK-9.12.0.aar",
          "size": 468649,
          "sha512": "def42d2f2ad37dd96b94fa671c025c34fb00bb846550e851122fef91eb8dc4e1e5ac489dfd3713d0fecd0a788c4100315472f6718eb796d71fa4bd08df1fa3f0",
          "sha256": "8f49ea16352c38a9816ca5a3450e69d133c9c4b48f86fd03b752916ceb00f506",
          "sha1": "070a1a8a76271e4df006e67c520facb6c18f4338",
          "md5": "58bdb156ddfec9c7b0707cd562cafef8"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.12.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.12.0.aar",
          "url": "FluctSDK-9.12.0.aar",
          "size": 468649,
          "sha512": "def42d2f2ad37dd96b94fa671c025c34fb00bb846550e851122fef91eb8dc4e1e5ac489dfd3713d0fecd0a788c4100315472f6718eb796d71fa4bd08df1fa3f0",
          "sha256": "8f49ea16352c38a9816ca5a3450e69d133c9c4b48f86fd03b752916ceb00f506",
          "sha1": "070a1a8a76271e4df006e67c520facb6c18f4338",
          "md5": "58bdb156ddfec9c7b0707cd562cafef8"
        }
      ]
    }
  ]
}
