{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.8.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.10]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.8.10.aar",
          "url": "fullscreen-ads-9.8.10.aar",
          "size": 143110,
          "sha512": "8313c4cc9c307d646d308f1de351167ca7436b227a419f5a510ca5f2ee9121c1b07ae84649bdb2d88aed870b19c56e83dc97d2c1ddfce2f3b74bcd5c6955124a",
          "sha256": "ee7be83a4786e1a8000aa1f52b69f0609de72c212bb6ff3bc041c033aef52a9f",
          "sha1": "6ff663cf1ccc536b63bb917a2805d93b7236ea4f",
          "md5": "4da9f7bd6cb06d5e52723d3c39efa706"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.10]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.8.10.aar",
          "url": "fullscreen-ads-9.8.10.aar",
          "size": 143110,
          "sha512": "8313c4cc9c307d646d308f1de351167ca7436b227a419f5a510ca5f2ee9121c1b07ae84649bdb2d88aed870b19c56e83dc97d2c1ddfce2f3b74bcd5c6955124a",
          "sha256": "ee7be83a4786e1a8000aa1f52b69f0609de72c212bb6ff3bc041c033aef52a9f",
          "sha1": "6ff663cf1ccc536b63bb917a2805d93b7236ea4f",
          "md5": "4da9f7bd6cb06d5e52723d3c39efa706"
        }
      ]
    }
  ]
}
