{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.14.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.14.0.aar",
          "url": "FluctSDK-9.14.0.aar",
          "size": 495343,
          "sha512": "322360d93c9b17aa6bd26ee35f0fe2bdb7b81193bf15b221cece24f34d130bbf044c67c4807d84b93b03ff5aca5d199b231d170131431addd5682a3e5b9c22b3",
          "sha256": "52221bb6bb66053d985b5d99ca416a029df238e06d40242624d75fdb1cc271cd",
          "sha1": "c2abbc8c40e330e1a305090716fa56d456035595",
          "md5": "e4b423df51957394ac26d3f101fab365"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.14.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.14.0.aar",
          "url": "FluctSDK-9.14.0.aar",
          "size": 495343,
          "sha512": "322360d93c9b17aa6bd26ee35f0fe2bdb7b81193bf15b221cece24f34d130bbf044c67c4807d84b93b03ff5aca5d199b231d170131431addd5682a3e5b9c22b3",
          "sha256": "52221bb6bb66053d985b5d99ca416a029df238e06d40242624d75fdb1cc271cd",
          "sha1": "c2abbc8c40e330e1a305090716fa56d456035595",
          "md5": "e4b423df51957394ac26d3f101fab365"
        }
      ]
    }
  ]
}
