{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation",
    "module": "rewardedvideo-mediation-maio",
    "version": "9.9.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-maio-9.9.1.aar",
          "url": "rewardedvideo-mediation-maio-9.9.1.aar",
          "size": 23511,
          "sha512": "fcedc35d40f5112b0e6c508bfe342b0bdceedf90a2293ad80e47fef155caa8ca01dac1b50e91df22fe9fc0c64b8f2a75787bc30914fb07ea1eb0796a2b599e7f",
          "sha256": "c4eff59e0699ac9dced0aa16c8aecde770a4bd27334e033b5f4806e0208d79cf",
          "sha1": "fc03516e0074ffc9b783ef572acf49dbca57388a",
          "md5": "c99d32110814da4d9cd918b7955d0228"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.maio",
          "module": "android-sdk",
          "version": {
            "requires": "1.1.16"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-maio-9.9.1.aar",
          "url": "rewardedvideo-mediation-maio-9.9.1.aar",
          "size": 23511,
          "sha512": "fcedc35d40f5112b0e6c508bfe342b0bdceedf90a2293ad80e47fef155caa8ca01dac1b50e91df22fe9fc0c64b8f2a75787bc30914fb07ea1eb0796a2b599e7f",
          "sha256": "c4eff59e0699ac9dced0aa16c8aecde770a4bd27334e033b5f4806e0208d79cf",
          "sha1": "fc03516e0074ffc9b783ef572acf49dbca57388a",
          "md5": "c99d32110814da4d9cd918b7955d0228"
        }
      ]
    }
  ]
}
