{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.9.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.4.aar",
          "url": "FluctSDK-9.9.4.aar",
          "size": 456275,
          "sha512": "16fb2297cb7fb27538453c5a3f52f96a8645f9197ca9af985523aaf860d66d1ee005839f8a2ea108ee7ebbfcd3ffd155d0b36ed89c2fbf7d509e8f5a383d72f3",
          "sha256": "2f1460d636d2e9d330f18fb1fc5d47b9117a31fd284f70687717a1de0e565b14",
          "sha1": "2c2a1bfb03a27857b94c19844158bdc51b586294",
          "md5": "ad7d02290797bc0be55c663d2d924d97"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.9.4]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.4.aar",
          "url": "FluctSDK-9.9.4.aar",
          "size": 456275,
          "sha512": "16fb2297cb7fb27538453c5a3f52f96a8645f9197ca9af985523aaf860d66d1ee005839f8a2ea108ee7ebbfcd3ffd155d0b36ed89c2fbf7d509e8f5a383d72f3",
          "sha256": "2f1460d636d2e9d330f18fb1fc5d47b9117a31fd284f70687717a1de0e565b14",
          "sha1": "2c2a1bfb03a27857b94c19844158bdc51b586294",
          "md5": "ad7d02290797bc0be55c663d2d924d97"
        }
      ]
    }
  ]
}
