{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.9.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.2.aar",
          "url": "FluctSDK-9.9.2.aar",
          "size": 456265,
          "sha512": "c7157ca6c9fdeda03439f926822169fd7594d5dd7b3278c88ba76edbad48db25f01985c8fd1b10c700b84e4af448d2c51c66870617b220b2d92e5d595236aa87",
          "sha256": "1a71df9a7c84066c517be27b62280be4f38441607e6952d3428f4d7ec3014c1a",
          "sha1": "5f9056ccf64a9311db8c37a05fd00e42b47b250a",
          "md5": "c6fd65872fe630e9f5dcfd62592e7ed6"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.9.2]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.2.aar",
          "url": "FluctSDK-9.9.2.aar",
          "size": 456265,
          "sha512": "c7157ca6c9fdeda03439f926822169fd7594d5dd7b3278c88ba76edbad48db25f01985c8fd1b10c700b84e4af448d2c51c66870617b220b2d92e5d595236aa87",
          "sha256": "1a71df9a7c84066c517be27b62280be4f38441607e6952d3428f4d7ec3014c1a",
          "sha1": "5f9056ccf64a9311db8c37a05fd00e42b47b250a",
          "md5": "c6fd65872fe630e9f5dcfd62592e7ed6"
        }
      ]
    }
  ]
}
