{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.applovin",
    "module": "applovin-adapter",
    "version": "9.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "11.5.1"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.8]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.8.8.aar",
          "url": "applovin-adapter-9.8.8.aar",
          "size": 13490,
          "sha512": "403f52dea6cae50e11645169962db979115fb8da8766c27477646637ea5517f708011fb095e520c25d3ee83920c7a1b0dad74dc8cd0920cfb87fd48c55b89cb8",
          "sha256": "77e004d3678626be41d11b765c54b300a768198372883552bd8194c91feedf7d",
          "sha1": "3576e5debd7816bf57c0ef96ae4f0f016642a325",
          "md5": "b7201907daf650893e2cacea4b0303a2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "11.5.1"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.8]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "9.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "applovin-adapter-9.8.8.aar",
          "url": "applovin-adapter-9.8.8.aar",
          "size": 13490,
          "sha512": "403f52dea6cae50e11645169962db979115fb8da8766c27477646637ea5517f708011fb095e520c25d3ee83920c7a1b0dad74dc8cd0920cfb87fd48c55b89cb8",
          "sha256": "77e004d3678626be41d11b765c54b300a768198372883552bd8194c91feedf7d",
          "sha1": "3576e5debd7816bf57c0ef96ae4f0f016642a325",
          "md5": "b7201907daf650893e2cacea4b0303a2"
        }
      ]
    }
  ]
}
