{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation",
    "module": "rewardedvideo-mediation-five",
    "version": "9.9.11",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.11]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-five-9.9.11.aar",
          "url": "rewardedvideo-mediation-five-9.9.11.aar",
          "size": 21108,
          "sha512": "9c20baa060f2c8b4f4cf36b89ead83eebb74b651567a5c2aaebb5fdf11df86d2d7ea1703ce74c2f01dd92ec1c0966ef4e2efa5a87e720cbc6e783cb76d17cc9f",
          "sha256": "b6486a1121a7afa99aab990d84759e7902ecfb44d4952da2f105c8efd636bdd0",
          "sha1": "0b414df5e4df6d7a4e1ad09cbae25833011f6b88",
          "md5": "9b3a79c2dbbc59718c3879a67cc67e37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.linecorp.adsnetwork",
          "module": "fivead",
          "version": {
            "requires": "2.7.20240214"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.11]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rewardedvideo-mediation-five-9.9.11.aar",
          "url": "rewardedvideo-mediation-five-9.9.11.aar",
          "size": 21108,
          "sha512": "9c20baa060f2c8b4f4cf36b89ead83eebb74b651567a5c2aaebb5fdf11df86d2d7ea1703ce74c2f01dd92ec1c0966ef4e2efa5a87e720cbc6e783cb76d17cc9f",
          "sha256": "b6486a1121a7afa99aab990d84759e7902ecfb44d4952da2f105c8efd636bdd0",
          "sha1": "0b414df5e4df6d7a4e1ad09cbae25833011f6b88",
          "md5": "9b3a79c2dbbc59718c3879a67cc67e37"
        }
      ]
    }
  ]
}
