{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.13.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.14.aar",
          "url": "FluctSDK-9.13.14.aar",
          "size": 493995,
          "sha512": "f03b76797b8e963e07ba5329a2412cf980a1d96efa71db5d2aa0d9e778d16c3c50ca1d27d174ef6933e4222eaeab533c8db210f0d9e789d50680f21c8c5f8cbf",
          "sha256": "42f53d15f884e5bd33264c74a3869f5b25a48d5659df615b736959e745920c7e",
          "sha1": "15c85ee7a2e1ce5673991c165b122298f1434ff5",
          "md5": "241b593642f4b5d11fe25a8d8e6947ef"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.13.14]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.13.14.aar",
          "url": "FluctSDK-9.13.14.aar",
          "size": 493995,
          "sha512": "f03b76797b8e963e07ba5329a2412cf980a1d96efa71db5d2aa0d9e778d16c3c50ca1d27d174ef6933e4222eaeab533c8db210f0d9e789d50680f21c8c5f8cbf",
          "sha256": "42f53d15f884e5bd33264c74a3869f5b25a48d5659df615b736959e745920c7e",
          "sha1": "15c85ee7a2e1ce5673991c165b122298f1434ff5",
          "md5": "241b593642f4b5d11fe25a8d8e6947ef"
        }
      ]
    }
  ]
}
