{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.7.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.7.0.aar",
          "url": "FluctSDK-9.7.0.aar",
          "size": 455625,
          "sha512": "daf01a4fbc0f5fd07e965dfa3b3b74588eed1f3db01c3d650525586cd6b95a0b77a0262d32bc5db249b23c19d3b6781eb3f5c9de4a1112e2961001002ee42939",
          "sha256": "4f0f5ed91f89b6613090ad0698ce848b84252cdbc8c05820db1f2788a2e0c082",
          "sha1": "5e2e8819684db082564e8626fc64e3c033ae3390",
          "md5": "774ef81e3a21d6d1c294efdc635630bd"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.7.0]"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.7.0.aar",
          "url": "FluctSDK-9.7.0.aar",
          "size": 455625,
          "sha512": "daf01a4fbc0f5fd07e965dfa3b3b74588eed1f3db01c3d650525586cd6b95a0b77a0262d32bc5db249b23c19d3b6781eb3f5c9de4a1112e2961001002ee42939",
          "sha256": "4f0f5ed91f89b6613090ad0698ce848b84252cdbc8c05820db1f2788a2e0c082",
          "sha1": "5e2e8819684db082564e8626fc64e3c033ae3390",
          "md5": "774ef81e3a21d6d1c294efdc635630bd"
        }
      ]
    }
  ]
}
