{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.9.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.3]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.9.3.aar",
          "url": "fullscreen-ads-9.9.3.aar",
          "size": 143695,
          "sha512": "6f07287a8fd104555c33c614362118ad79f21ab4cc7091d309a8ba6d628927cbdb05188d7b4ec604c4b8661c56d7d259f8ce86f035bd41a1e1ffbacf37194db1",
          "sha256": "82f8c4574ddded1c8e86047aa2a4588dbd6bb05d1b31dfd0fcca06879ae609fe",
          "sha1": "a12638780ae0f9a2c94c8355dcd4769545ed20e3",
          "md5": "92c69d5c93423f890df449b63939d1ee"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.9.3]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.9.3.aar",
          "url": "fullscreen-ads-9.9.3.aar",
          "size": 143695,
          "sha512": "6f07287a8fd104555c33c614362118ad79f21ab4cc7091d309a8ba6d628927cbdb05188d7b4ec604c4b8661c56d7d259f8ce86f035bd41a1e1ffbacf37194db1",
          "sha256": "82f8c4574ddded1c8e86047aa2a4588dbd6bb05d1b31dfd0fcca06879ae609fe",
          "sha1": "a12638780ae0f9a2c94c8355dcd4769545ed20e3",
          "md5": "92c69d5c93423f890df449b63939d1ee"
        }
      ]
    }
  ]
}
