{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.13.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.5]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.5.aar",
          "url": "fullscreen-ads-9.13.5.aar",
          "size": 143516,
          "sha512": "ca54c98cb098b4fab59283d5a5277c8f990e0e56213547d71c9e3f7a8a2f326ba9ab37665efb2032eee42c697ce00aa0dae03f9e915b98902d3b01617ace9f59",
          "sha256": "c67be75056109b904cc26f212feaff78723cfcb0c514c130997a8a7fab878d5f",
          "sha1": "f968524e16f24a34555384e73fac1a0902dec9f8",
          "md5": "6c0aa2bf6ef9f29715897012610f3770"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.5]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.5.aar",
          "url": "fullscreen-ads-9.13.5.aar",
          "size": 143516,
          "sha512": "ca54c98cb098b4fab59283d5a5277c8f990e0e56213547d71c9e3f7a8a2f326ba9ab37665efb2032eee42c697ce00aa0dae03f9e915b98902d3b01617ace9f59",
          "sha256": "c67be75056109b904cc26f212feaff78723cfcb0c514c130997a8a7fab878d5f",
          "sha1": "f968524e16f24a34555384e73fac1a0902dec9f8",
          "md5": "6c0aa2bf6ef9f29715897012610f3770"
        }
      ]
    }
  ]
}
