{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.16.1]"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.16.1.aar",
          "url": "FluctSDK-9.16.1.aar",
          "size": 458141,
          "sha512": "4a03284e7f3000e4b83fedcc0e67935af334a9c62355525abd33df96a04a54deffda39224e8987089deccb951073ed492725f90f06c2da4a2b6411db00af7f4a",
          "sha256": "70de458043aaf566f107fa29f85a823b245a24fccf415e3db362c5e2e6e8ded3",
          "sha1": "7c06e15ab8203e71c15410f183288f4bfc69bd42",
          "md5": "afc9cfed0b7fbb09dc259cd79fdfa9f8"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.16.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "shared",
          "version": {
            "requires": "[9.16.1]"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.16.1.aar",
          "url": "FluctSDK-9.16.1.aar",
          "size": 458141,
          "sha512": "4a03284e7f3000e4b83fedcc0e67935af334a9c62355525abd33df96a04a54deffda39224e8987089deccb951073ed492725f90f06c2da4a2b6411db00af7f4a",
          "sha256": "70de458043aaf566f107fa29f85a823b245a24fccf415e3db362c5e2e6e8ded3",
          "sha1": "7c06e15ab8203e71c15410f183288f4bfc69bd42",
          "md5": "afc9cfed0b7fbb09dc259cd79fdfa9f8"
        }
      ]
    }
  ]
}
