{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.13.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.4]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.4.aar",
          "url": "fullscreen-ads-9.13.4.aar",
          "size": 143520,
          "sha512": "80f9e9f2977c26ed7255ef6b5bcc5fa084b6a682b9226d274ee9182202d02c21a655a9d02ada155d225d3d17a24812d9d39ee2b413d85d4b689442d65523ce7f",
          "sha256": "269d1ccfa8a89bba5332c31168d5778925dbcdd7423a1b4fd56cf3bdebb09ecb",
          "sha1": "0521eaf08c2d25eb213a194e0389793a869b88a5",
          "md5": "0f7d504927b83e2f2cb9b93ffb0b145b"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.4]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.4.aar",
          "url": "fullscreen-ads-9.13.4.aar",
          "size": 143520,
          "sha512": "80f9e9f2977c26ed7255ef6b5bcc5fa084b6a682b9226d274ee9182202d02c21a655a9d02ada155d225d3d17a24812d9d39ee2b413d85d4b689442d65523ce7f",
          "sha256": "269d1ccfa8a89bba5332c31168d5778925dbcdd7423a1b4fd56cf3bdebb09ecb",
          "sha1": "0521eaf08c2d25eb213a194e0389793a869b88a5",
          "md5": "0f7d504927b83e2f2cb9b93ffb0b145b"
        }
      ]
    }
  ]
}
