{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.3.0.aar",
          "url": "FluctSDK-9.3.0.aar",
          "size": 572569,
          "sha512": "8e03438b174e5f276ff327d9698dc91b82a99dee8155364c8e9c5c4c4ca5a8c3dadd0dde3d72e4e60bd4b6ce0dbc050667eeb3aec1a3e1acf90ab97ab2d3320f",
          "sha256": "ab90d9f7198088262a7a0a8448b1a1ad9d3bb81065b23e20fc2fe7c0b25442cb",
          "sha1": "6d554f94d7050aafe2405e705a56146f2911254a",
          "md5": "a5ad76906adea53e9f66705b6b6c2d6d"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "9.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.3.0.aar",
          "url": "FluctSDK-9.3.0.aar",
          "size": 572569,
          "sha512": "8e03438b174e5f276ff327d9698dc91b82a99dee8155364c8e9c5c4c4ca5a8c3dadd0dde3d72e4e60bd4b6ce0dbc050667eeb3aec1a3e1acf90ab97ab2d3320f",
          "sha256": "ab90d9f7198088262a7a0a8448b1a1ad9d3bb81065b23e20fc2fe7c0b25442cb",
          "sha1": "6d554f94d7050aafe2405e705a56146f2911254a",
          "md5": "a5ad76906adea53e9f66705b6b6c2d6d"
        }
      ]
    }
  ]
}
