{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.8.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.8.5.aar",
          "url": "FluctSDK-9.8.5.aar",
          "size": 454593,
          "sha512": "da7e6bd2d13dba2775fd67d8cb3e19b5e498b03791974652ec76257056eabb29078d7bbfff0e958ceabc9e9ec3b940cae13c9f1b3c6d2a4c47a4e161b993b1d1",
          "sha256": "9212700e9b29723a191bf6af155a3a9721d18b4f1db513346f5015b810bbf3e4",
          "sha1": "4eae82c2d458ad51e7d9780a1dc45fad00885669",
          "md5": "15801a79597c40fe3679aac3c029a583"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.8.5]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.8.5.aar",
          "url": "FluctSDK-9.8.5.aar",
          "size": 454593,
          "sha512": "da7e6bd2d13dba2775fd67d8cb3e19b5e498b03791974652ec76257056eabb29078d7bbfff0e958ceabc9e9ec3b940cae13c9f1b3c6d2a4c47a4e161b993b1d1",
          "sha256": "9212700e9b29723a191bf6af155a3a9721d18b4f1db513346f5015b810bbf3e4",
          "sha1": "4eae82c2d458ad51e7d9780a1dc45fad00885669",
          "md5": "15801a79597c40fe3679aac3c029a583"
        }
      ]
    }
  ]
}
