{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.4.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.4.7.aar",
          "url": "FluctSDK-9.4.7.aar",
          "size": 449942,
          "sha512": "2d03c6086c28a4eff69c5f76bf3d7c7ab454eabcad95144eeb62f5775e2f98561364d5c128c5693147df554f6ef2552da72a91cd8b205e99ed07885e5a7f1f81",
          "sha256": "2b4129c0686b2c94167a690b85f2832bbec5484206aa852d701a1d1aa2fe7451",
          "sha1": "708cd89eca2ba2ac931fba0a7b280decd9416d76",
          "md5": "ca34edb1cd72d109cf5c84a882cbcc41"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "9.4.7"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.4.7.aar",
          "url": "FluctSDK-9.4.7.aar",
          "size": 449942,
          "sha512": "2d03c6086c28a4eff69c5f76bf3d7c7ab454eabcad95144eeb62f5775e2f98561364d5c128c5693147df554f6ef2552da72a91cd8b205e99ed07885e5a7f1f81",
          "sha256": "2b4129c0686b2c94167a690b85f2832bbec5484206aa852d701a1d1aa2fe7451",
          "sha1": "708cd89eca2ba2ac931fba0a7b280decd9416d76",
          "md5": "ca34edb1cd72d109cf5c84a882cbcc41"
        }
      ]
    }
  ]
}
