{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.4.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.4.3.aar",
          "url": "FluctSDK-9.4.3.aar",
          "size": 452332,
          "sha512": "3bc34627da191bfe73df9525cd66fa400c9b111ad80d6f3bf4690d2bf19aa9d9df1acebce3be9d650ac2a2c13995f20388c00f04b25aa0b6f147b21374274edf",
          "sha256": "84798e5765355524528f526be4382a412410cebb92b59be9837147ab252e828c",
          "sha1": "793ac06248ad282cc1a9d2bc5bbddae3a8d43a82",
          "md5": "b252403c810af8579ca36a4cf98635c1"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "9.4.3"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.4.3.aar",
          "url": "FluctSDK-9.4.3.aar",
          "size": 452332,
          "sha512": "3bc34627da191bfe73df9525cd66fa400c9b111ad80d6f3bf4690d2bf19aa9d9df1acebce3be9d650ac2a2c13995f20388c00f04b25aa0b6f147b21374274edf",
          "sha256": "84798e5765355524528f526be4382a412410cebb92b59be9837147ab252e828c",
          "sha1": "793ac06248ad282cc1a9d2bc5bbddae3a8d43a82",
          "md5": "b252403c810af8579ca36a4cf98635c1"
        }
      ]
    }
  ]
}
