{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation.gma",
    "module": "gma-mediation",
    "version": "9.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.1]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.8.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.8.1.aar",
          "url": "gma-mediation-9.8.1.aar",
          "size": 50157,
          "sha512": "0cf2701574c1fc548d99d989b327b78c565ec7ec095b605b102767450543aea2e2345a29ef80cb9b4fb10a308a9180d71871f34a8747f3ac45bf3fc1aa797e6f",
          "sha256": "408951da1b7d1a1a601d2579bd9b0b9cf9382e721d4bd127daad763ec0647222",
          "sha1": "e14ad4348e291dd428c9740a7ffb411b64ccb539",
          "md5": "38b27302c02d90fe8774913dc59a390b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "22.0.0"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.1]"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "fullscreen-ads",
          "version": {
            "requires": "[9.8.1]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "gma-mediation-9.8.1.aar",
          "url": "gma-mediation-9.8.1.aar",
          "size": 50157,
          "sha512": "0cf2701574c1fc548d99d989b327b78c565ec7ec095b605b102767450543aea2e2345a29ef80cb9b4fb10a308a9180d71871f34a8747f3ac45bf3fc1aa797e6f",
          "sha256": "408951da1b7d1a1a601d2579bd9b0b9cf9382e721d4bd127daad763ec0647222",
          "sha1": "e14ad4348e291dd428c9740a7ffb411b64ccb539",
          "md5": "38b27302c02d90fe8774913dc59a390b"
        }
      ]
    }
  ]
}
