{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.13.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.8]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.8.aar",
          "url": "fullscreen-ads-9.13.8.aar",
          "size": 143524,
          "sha512": "c85185b25287c890b027054e01fc7e8d01d407e24a79288a0b7cbcbb95ca959b002122e70a52523aa805f0195767ac53a7873534f26f04ff98b404327be95252",
          "sha256": "e6e24eec34f9113039718c8e5d0039ab9f3dfb341383d4abd4880b511582fb04",
          "sha1": "2c256941079425b03d6e5682bbc09b0863cc8048",
          "md5": "63f71d40b9577ebe9f87f7f4f2f1c29b"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "null"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.13.8]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.13.8.aar",
          "url": "fullscreen-ads-9.13.8.aar",
          "size": 143524,
          "sha512": "c85185b25287c890b027054e01fc7e8d01d407e24a79288a0b7cbcbb95ca959b002122e70a52523aa805f0195767ac53a7873534f26f04ff98b404327be95252",
          "sha256": "e6e24eec34f9113039718c8e5d0039ab9f3dfb341383d4abd4880b511582fb04",
          "sha1": "2c256941079425b03d6e5682bbc09b0863cc8048",
          "md5": "63f71d40b9577ebe9f87f7f4f2f1c29b"
        }
      ]
    }
  ]
}
