{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "8.12.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "jjyx4aanjzfddpmvsvb6c5wxmm"
    }
  },
  "variants": [
    {
      "name": "productionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "FluctSDK-8.12.1.aar",
          "url": "FluctSDK-8.12.1.aar",
          "size": 580135,
          "sha512": "b987f6f6e6e9ddf345fcdebf25294f70988525b694f284790668a5cdc007ec688fe951fb39391aad216750055ead6acce608ad9a6c5c2923bd7796d200ec05c7",
          "sha256": "9deca4af89a7199b2ab070e2487ea53d9d16bdd2f643e2b8aff355793fa30d61",
          "sha1": "aa25b4889adf10a22e6a2410ce9ef6752b2515b1",
          "md5": "d575ee0572906e61d1f01c09abb2ce5f"
        }
      ]
    },
    {
      "name": "productionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "16.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-annotations",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "support-v4",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "appcompat-v7",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.android.support",
          "module": "webkit",
          "version": {
            "requires": "28.0.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "8.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-8.12.1.aar",
          "url": "FluctSDK-8.12.1.aar",
          "size": 580135,
          "sha512": "b987f6f6e6e9ddf345fcdebf25294f70988525b694f284790668a5cdc007ec688fe951fb39391aad216750055ead6acce608ad9a6c5c2923bd7796d200ec05c7",
          "sha256": "9deca4af89a7199b2ab070e2487ea53d9d16bdd2f643e2b8aff355793fa30d61",
          "sha1": "aa25b4889adf10a22e6a2410ce9ef6752b2515b1",
          "md5": "d575ee0572906e61d1f01c09abb2ce5f"
        }
      ]
    }
  ]
}
