{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.12.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.12.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.12.0.aar",
          "url": "fullscreen-ads-9.12.0.aar",
          "size": 144233,
          "sha512": "ecc37fc42f95fb0e45fddba46ca7778b5a771a72b21859fcf18d687ef6bf7ded566ca2fc7d54ef69591b5f55d0811541e2e4bb5e746b50db21d3a68ae0bd3da2",
          "sha256": "792b343c40fbd18706f9c6c02f85fccab4b3c86b56f6eae8d19bb9537ffbf09f",
          "sha1": "6bf10bb67d228b27a5eb00a5b6cba6eac44966a3",
          "md5": "20761827c334029cf7ecfec81a0c4126"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.12.0]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.12.0.aar",
          "url": "fullscreen-ads-9.12.0.aar",
          "size": 144233,
          "sha512": "ecc37fc42f95fb0e45fddba46ca7778b5a771a72b21859fcf18d687ef6bf7ded566ca2fc7d54ef69591b5f55d0811541e2e4bb5e746b50db21d3a68ae0bd3da2",
          "sha256": "792b343c40fbd18706f9c6c02f85fccab4b3c86b56f6eae8d19bb9537ffbf09f",
          "sha1": "6bf10bb67d228b27a5eb00a5b6cba6eac44966a3",
          "md5": "20761827c334029cf7ecfec81a0c4126"
        }
      ]
    }
  ]
}
