{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.9.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.6.aar",
          "url": "FluctSDK-9.9.6.aar",
          "size": 455641,
          "sha512": "70d4439104d156288e4682cfd45fc2bb18234a60af4559ac48e5a55799915b24f9ae897f3e64f47c9893ac0c42b73cb7392ef177b7f69403821c10b1310b4f43",
          "sha256": "8e722d101a7c6d86122c1c1f85228b1d5e8fd1e4155f6cb22b98f1bd73a5440e",
          "sha1": "9e267d2a6db658ecd9b67bdefd5e2eb5a57d113b",
          "md5": "09741a6391c721dd1e81041deac89462"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "[9.9.6]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.9.6.aar",
          "url": "FluctSDK-9.9.6.aar",
          "size": 455641,
          "sha512": "70d4439104d156288e4682cfd45fc2bb18234a60af4559ac48e5a55799915b24f9ae897f3e64f47c9893ac0c42b73cb7392ef177b7f69403821c10b1310b4f43",
          "sha256": "8e722d101a7c6d86122c1c1f85228b1d5e8fd1e4155f6cb22b98f1bd73a5440e",
          "sha1": "9e267d2a6db658ecd9b67bdefd5e2eb5a57d113b",
          "md5": "09741a6391c721dd1e81041deac89462"
        }
      ]
    }
  ]
}
