{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.mediation",
    "module": "videointerstitial-mediation-unityads",
    "version": "9.8.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.0]"
          }
        }
      ],
      "files": [
        {
          "name": "videointerstitial-mediation-unityads-9.8.0.aar",
          "url": "videointerstitial-mediation-unityads-9.8.0.aar",
          "size": 14812,
          "sha512": "14bb5dfb008692bbdbd5ef63d0c2dd58bfc283383223c0c06c780551e285063870dd41e0d7af750e2d99b326d0de24b49d4377d2bb86edf2f60c450e25996037",
          "sha256": "21771b4acaf0b23588441af0b7b569490b2e2da841b373f9f11fbab1c11161d1",
          "sha1": "53cb63db67d026e50f7d79490886a16e320a37f9",
          "md5": "17a4db03bea741d8f82267d25a8540da"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.unity3d.ads",
          "module": "unity-ads",
          "version": {
            "requires": "4.6.0"
          }
        },
        {
          "group": "jp.fluct.mediation",
          "module": "rewardedvideo-mediation-unityads",
          "version": {
            "requires": "[9.8.0]"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.0]"
          }
        }
      ],
      "files": [
        {
          "name": "videointerstitial-mediation-unityads-9.8.0.aar",
          "url": "videointerstitial-mediation-unityads-9.8.0.aar",
          "size": 14812,
          "sha512": "14bb5dfb008692bbdbd5ef63d0c2dd58bfc283383223c0c06c780551e285063870dd41e0d7af750e2d99b326d0de24b49d4377d2bb86edf2f60c450e25996037",
          "sha256": "21771b4acaf0b23588441af0b7b569490b2e2da841b373f9f11fbab1c11161d1",
          "sha1": "53cb63db67d026e50f7d79490886a16e320a37f9",
          "md5": "17a4db03bea741d8f82267d25a8540da"
        }
      ]
    }
  ]
}
