{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct",
    "module": "FluctSDK",
    "version": "9.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "productionReleaseVariantProductionReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.2.0.aar",
          "url": "FluctSDK-9.2.0.aar",
          "size": 572701,
          "sha512": "32b96d1d67be66e2671574a8fe57954f7252739c0a39cade7339c17a18287abb6d7c8343c342524986cfa2ea6aa6711f41483b579d3124863909cbfa9710ded5",
          "sha256": "69c8386529794c906eaaa9318b8007d5b92edb1f8c485fae3e9e2185ed35048a",
          "sha1": "93022bdbcf97cb221467b87b6ebaa007bb15a81b",
          "md5": "04679ec1ba2feae69436fa7559c88ce8"
        }
      ]
    },
    {
      "name": "productionReleaseVariantProductionReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "strictly": "[1.5.0,)",
            "requires": "[1.5.0,)",
            "prefers": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "strictly": "[1.3.1,)",
            "requires": "[1.3.1,)",
            "prefers": "1.4.2"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "androidx.webkit",
          "module": "webkit",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct.fluctsdk",
          "module": "event-logger",
          "version": {
            "requires": "9.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "FluctSDK-9.2.0.aar",
          "url": "FluctSDK-9.2.0.aar",
          "size": 572701,
          "sha512": "32b96d1d67be66e2671574a8fe57954f7252739c0a39cade7339c17a18287abb6d7c8343c342524986cfa2ea6aa6711f41483b579d3124863909cbfa9710ded5",
          "sha256": "69c8386529794c906eaaa9318b8007d5b92edb1f8c485fae3e9e2185ed35048a",
          "sha1": "93022bdbcf97cb221467b87b6ebaa007bb15a81b",
          "md5": "04679ec1ba2feae69436fa7559c88ce8"
        }
      ]
    }
  ]
}
