{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.8.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.7]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.8.7.aar",
          "url": "fullscreen-ads-9.8.7.aar",
          "size": 142750,
          "sha512": "b9a748e5ac920f0e359e3ebb8b9d98e0c0a8d8dac7dacfa79fbb70d4e3bd4c3d998b9bf99618e7f4bac4bf3d1e1671497f5405542a712e96d279cbdb361190c2",
          "sha256": "ed082b0b77093947bfe67d0c14b0b32008a55735776c426d75af29670d5f7288",
          "sha1": "91c293f2509f0bb8aca476f6aed603ab283a19d8",
          "md5": "7aeb12f621488916afe2c4f029bae873"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.7]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.8.7.aar",
          "url": "fullscreen-ads-9.8.7.aar",
          "size": 142750,
          "sha512": "b9a748e5ac920f0e359e3ebb8b9d98e0c0a8d8dac7dacfa79fbb70d4e3bd4c3d998b9bf99618e7f4bac4bf3d1e1671497f5405542a712e96d279cbdb361190c2",
          "sha256": "ed082b0b77093947bfe67d0c14b0b32008a55735776c426d75af29670d5f7288",
          "sha1": "91c293f2509f0bb8aca476f6aed603ab283a19d8",
          "md5": "7aeb12f621488916afe2c4f029bae873"
        }
      ]
    }
  ]
}
