{
  "formatVersion": "1.1",
  "component": {
    "group": "jp.fluct.fluctsdk",
    "module": "fullscreen-ads",
    "version": "9.8.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.8]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.8.8.aar",
          "url": "fullscreen-ads-9.8.8.aar",
          "size": 142756,
          "sha512": "d11c913d4275483e7ee181981980ec0929e326357cba637b009f0e3f20bbeb05f7686676571efa08f940a395a4a653831b9277844fcd3a81eb416ff50cdf7abd",
          "sha256": "fc722cc236997b5c1d15f8e1c1a283814bd34412e28df4ef58a856ca3ce1c882",
          "sha1": "c0e28d6194e22ab9d651cc02a0ae4d00e2ac97fa",
          "md5": "57f1ed6e83045cc800ec5a029378972d"
        }
      ]
    },
    {
      "name": "exoplayerDefaultReleaseVariantExoplayerDefaultReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-core",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer-ui",
          "version": {
            "requires": "2.18.1"
          }
        },
        {
          "group": "com.iab.omid.library",
          "module": "fluctjp",
          "version": {
            "requires": "1.3.19"
          }
        },
        {
          "group": "jp.fluct",
          "module": "FluctSDK",
          "version": {
            "requires": "[9.8.8]"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "fullscreen-ads-9.8.8.aar",
          "url": "fullscreen-ads-9.8.8.aar",
          "size": 142756,
          "sha512": "d11c913d4275483e7ee181981980ec0929e326357cba637b009f0e3f20bbeb05f7686676571efa08f940a395a4a653831b9277844fcd3a81eb416ff50cdf7abd",
          "sha256": "fc722cc236997b5c1d15f8e1c1a283814bd34412e28df4ef58a856ca3ce1c882",
          "sha1": "c0e28d6194e22ab9d651cc02a0ae4d00e2ac97fa",
          "md5": "57f1ed6e83045cc800ec5a029378972d"
        }
      ]
    }
  ]
}
